/*
 * This file was automatically generated by EvoSuite
 * Mon Nov 22 08:53:41 GMT 2021
 */

package com.facebook.presto.redis;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import com.facebook.airlift.json.JsonCodec;
import com.facebook.presto.redis.RedisConnectorConfig;
import com.facebook.presto.redis.RedisTableDescription;
import com.facebook.presto.redis.RedisTableDescriptionSupplier;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class RedisTableDescriptionSupplier_ESTest extends RedisTableDescriptionSupplier_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      RedisConnectorConfig redisConnectorConfig0 = new RedisConnectorConfig();
      RedisTableDescriptionSupplier redisTableDescriptionSupplier0 = null;
      try {
        redisTableDescriptionSupplier0 = new RedisTableDescriptionSupplier(redisConnectorConfig0, (JsonCodec<RedisTableDescription>) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // tableDescriptionCodec is null
         //
         verifyException("java.util.Objects", e);
      }
  }
}
