/*
 * This file was automatically generated by EvoSuite
 * Thu Nov 18 22:34:49 GMT 2021
 */

package com.facebook.presto.spark.classloader_interface;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import com.facebook.presto.spark.classloader_interface.SerializedPrestoSparkTaskDescriptor;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class SerializedPrestoSparkTaskDescriptor_ESTest extends SerializedPrestoSparkTaskDescriptor_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      byte[] byteArray0 = new byte[3];
      SerializedPrestoSparkTaskDescriptor serializedPrestoSparkTaskDescriptor0 = new SerializedPrestoSparkTaskDescriptor(byteArray0);
      byte[] byteArray1 = serializedPrestoSparkTaskDescriptor0.getBytes();
      assertEquals(3, byteArray1.length);
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      byte[] byteArray0 = new byte[0];
      SerializedPrestoSparkTaskDescriptor serializedPrestoSparkTaskDescriptor0 = new SerializedPrestoSparkTaskDescriptor(byteArray0);
      byte[] byteArray1 = serializedPrestoSparkTaskDescriptor0.getBytes();
      assertArrayEquals(new byte[] {}, byteArray1);
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      SerializedPrestoSparkTaskDescriptor serializedPrestoSparkTaskDescriptor0 = null;
      try {
        serializedPrestoSparkTaskDescriptor0 = new SerializedPrestoSparkTaskDescriptor((byte[]) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // bytes is null
         //
         verifyException("java.util.Objects", e);
      }
  }
}
