/*
 * This file was automatically generated by EvoSuite
 * Mon Nov 22 19:45:36 GMT 2021
 */

package com.facebook.presto.tests;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import com.facebook.presto.tests.TlsTests;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class TlsTests_ESTest extends TlsTests_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      TlsTests tlsTests0 = new TlsTests();
      // Undeclared exception!
      try { 
        tlsTests0.testHttpPortIsClosed();
        fail("Expecting exception: AssertionError");
      
      } catch(AssertionError e) {
      }
  }
}
