/*
 * This file was automatically generated by EvoSuite
 * Sun Nov 21 00:20:09 GMT 2021
 */

package com.facebook.presto.kafka.schema.file;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import com.facebook.airlift.json.JsonCodec;
import com.facebook.presto.kafka.KafkaConnectorConfig;
import com.facebook.presto.kafka.KafkaTopicDescription;
import com.facebook.presto.kafka.schema.file.FileTableDescriptionSupplier;
import com.facebook.presto.kafka.schema.file.FileTableDescriptionSupplierConfig;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class FileTableDescriptionSupplier_ESTest extends FileTableDescriptionSupplier_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      FileTableDescriptionSupplier fileTableDescriptionSupplier0 = null;
      try {
        fileTableDescriptionSupplier0 = new FileTableDescriptionSupplier((FileTableDescriptionSupplierConfig) null, (KafkaConnectorConfig) null, (JsonCodec<KafkaTopicDescription>) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // topicDescriptionCodec is null
         //
         verifyException("java.util.Objects", e);
      }
  }
}
