/*
 * This file was automatically generated by EvoSuite
 * Sun Nov 21 03:42:13 GMT 2021
 */

package com.facebook.presto.example;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import com.facebook.presto.common.type.Type;
import com.facebook.presto.example.ExampleColumn;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class ExampleColumn_ESTest extends ExampleColumn_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      ExampleColumn exampleColumn0 = null;
      try {
        exampleColumn0 = new ExampleColumn("u", (Type) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // type is null
         //
         verifyException("java.util.Objects", e);
      }
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      ExampleColumn exampleColumn0 = null;
      try {
        exampleColumn0 = new ExampleColumn((String) null, (Type) null);
        fail("Expecting exception: IllegalArgumentException");
      
      } catch(IllegalArgumentException e) {
         //
         // name is null or is empty
         //
         verifyException("com.google.common.base.Preconditions", e);
      }
  }
}
