/*
 * This file was automatically generated by EvoSuite
 * Sat Nov 20 22:15:53 GMT 2021
 */

package com.facebook.presto.example;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import com.facebook.presto.example.ExampleClient;
import com.facebook.presto.example.ExampleConnectorId;
import com.facebook.presto.example.ExampleSplitManager;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class ExampleSplitManager_ESTest extends ExampleSplitManager_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      ExampleSplitManager exampleSplitManager0 = null;
      try {
        exampleSplitManager0 = new ExampleSplitManager((ExampleConnectorId) null, (ExampleClient) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // connectorId is null
         //
         verifyException("java.util.Objects", e);
      }
  }
}
