/*
 * This file was automatically generated by EvoSuite
 * Sat Nov 20 17:49:16 GMT 2021
 */

package com.facebook.presto.resourceGroups.db;

import org.junit.Test;
import static org.junit.Assert.*;
import com.facebook.presto.resourceGroups.db.DbResourceGroupConfig;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class DbResourceGroupConfig_ESTest extends DbResourceGroupConfig_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      DbResourceGroupConfig dbResourceGroupConfig0 = new DbResourceGroupConfig();
      DbResourceGroupConfig dbResourceGroupConfig1 = dbResourceGroupConfig0.setConfigDbUrl("");
      String string0 = dbResourceGroupConfig1.getConfigDbUrl();
      assertEquals("", string0);
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      DbResourceGroupConfig dbResourceGroupConfig0 = new DbResourceGroupConfig();
      String string0 = dbResourceGroupConfig0.getConfigDbUrl();
      assertNull(string0);
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      DbResourceGroupConfig dbResourceGroupConfig0 = new DbResourceGroupConfig();
      DbResourceGroupConfig dbResourceGroupConfig1 = dbResourceGroupConfig0.setConfigDbUrl("com.facebook.presto.resourceGroups.db.DbResourceGroupConfig");
      String string0 = dbResourceGroupConfig1.getConfigDbUrl();
      assertEquals("com.facebook.presto.resourceGroups.db.DbResourceGroupConfig", string0);
  }
}
