/*
 * This file was automatically generated by EvoSuite
 * Mon Nov 22 18:49:56 GMT 2021
 */

package com.facebook.presto.jdbc;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import com.facebook.presto.jdbc.ColumnInfo;
import com.facebook.presto.jdbc.PrestoResultSetMetaData;
import java.util.List;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class PrestoResultSetMetaData_ESTest extends PrestoResultSetMetaData_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      PrestoResultSetMetaData prestoResultSetMetaData0 = null;
      try {
        prestoResultSetMetaData0 = new PrestoResultSetMetaData((List<ColumnInfo>) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // columnInfo is null
         //
         verifyException("java.util.Objects", e);
      }
  }
}
