/*
 * This file was automatically generated by EvoSuite
 * Mon Nov 22 18:56:39 GMT 2021
 */

package com.facebook.presto.jdbc;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import com.facebook.presto.jdbc.StageStats;
import java.util.List;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class StageStats_ESTest extends StageStats_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      // Undeclared exception!
      try { 
        StageStats.create((com.facebook.presto.client.StageStats) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("com.facebook.presto.jdbc.StageStats", e);
      }
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      StageStats stageStats0 = null;
      try {
        stageStats0 = new StageStats("wR^g$g9wt=2kj", "wR^g$g9wt=2kj", true, 0, 0, 0, 0, 0, 0, 0, 0, 0, (List<StageStats>) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // subStages is null
         //
         verifyException("java.util.Objects", e);
      }
  }
}
