/*
 * This file was automatically generated by EvoSuite
 * Sat Nov 20 18:24:11 GMT 2021
 */

package com.facebook.presto.orc.stream;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import com.facebook.presto.orc.stream.BooleanInputStream;
import com.facebook.presto.orc.stream.OrcInputStream;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class BooleanInputStream_ESTest extends BooleanInputStream_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      BooleanInputStream booleanInputStream0 = null;
      try {
        booleanInputStream0 = new BooleanInputStream((OrcInputStream) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("com.facebook.presto.orc.stream.ByteInputStream", e);
      }
  }
}
