/*
 * This file was automatically generated by EvoSuite
 * Sun Nov 21 00:19:52 GMT 2021
 */

package com.facebook.presto.kafka.encoder.avro;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import com.facebook.presto.kafka.encoder.EncoderColumnHandle;
import com.facebook.presto.kafka.encoder.avro.AvroRowEncoder;
import com.facebook.presto.spi.ConnectorSession;
import java.util.List;
import org.apache.avro.Schema;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class AvroRowEncoder_ESTest extends AvroRowEncoder_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      AvroRowEncoder avroRowEncoder0 = null;
      try {
        avroRowEncoder0 = new AvroRowEncoder((ConnectorSession) null, (List<EncoderColumnHandle>) null, (Schema) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // session is null
         //
         verifyException("java.util.Objects", e);
      }
  }
}
