/*
 * This file was automatically generated by EvoSuite
 * Sat Nov 20 23:58:08 GMT 2021
 */

package com.facebook.presto.connector.jmx;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import com.facebook.presto.connector.jmx.JmxConnectorConfig;
import io.airlift.units.Duration;
import java.util.Set;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class JmxConnectorConfig_ESTest extends JmxConnectorConfig_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test00()  throws Throwable  {
      JmxConnectorConfig jmxConnectorConfig0 = new JmxConnectorConfig();
      Set<String> set0 = jmxConnectorConfig0.getDumpTables();
      assertEquals(86400, jmxConnectorConfig0.getMaxEntries());
      
      JmxConnectorConfig jmxConnectorConfig1 = jmxConnectorConfig0.setMaxEntries(0);
      jmxConnectorConfig1.setDumpTables(set0);
      assertEquals(0, jmxConnectorConfig0.getMaxEntries());
  }

  @Test(timeout = 4000)
  public void test01()  throws Throwable  {
      JmxConnectorConfig jmxConnectorConfig0 = new JmxConnectorConfig();
      jmxConnectorConfig0.setMaxEntries((-3591));
      Set<String> set0 = jmxConnectorConfig0.getDumpTables();
      jmxConnectorConfig0.setDumpTables(set0);
      assertEquals((-3591), jmxConnectorConfig0.getMaxEntries());
  }

  @Test(timeout = 4000)
  public void test02()  throws Throwable  {
      JmxConnectorConfig jmxConnectorConfig0 = new JmxConnectorConfig();
      assertEquals(86400, jmxConnectorConfig0.getMaxEntries());
      
      JmxConnectorConfig jmxConnectorConfig1 = jmxConnectorConfig0.setMaxEntries(0);
      jmxConnectorConfig1.setDumpTables("expectedSize");
      assertEquals(0, jmxConnectorConfig0.getMaxEntries());
  }

  @Test(timeout = 4000)
  public void test03()  throws Throwable  {
      JmxConnectorConfig jmxConnectorConfig0 = new JmxConnectorConfig();
      jmxConnectorConfig0.setMaxEntries((-2320));
      jmxConnectorConfig0.setDumpTables("com.google.common.collect.ImmutableSet$RegularSetBuilderImpl");
      assertEquals((-2320), jmxConnectorConfig0.getMaxEntries());
  }

  @Test(timeout = 4000)
  public void test04()  throws Throwable  {
      JmxConnectorConfig jmxConnectorConfig0 = new JmxConnectorConfig();
      assertEquals(86400, jmxConnectorConfig0.getMaxEntries());
      
      jmxConnectorConfig0.setMaxEntries(0);
      jmxConnectorConfig0.setDumpPeriod((Duration) null);
      assertEquals(0, jmxConnectorConfig0.getMaxEntries());
  }

  @Test(timeout = 4000)
  public void test05()  throws Throwable  {
      JmxConnectorConfig jmxConnectorConfig0 = new JmxConnectorConfig();
      jmxConnectorConfig0.setMaxEntries((-2320));
      jmxConnectorConfig0.setDumpPeriod((Duration) null);
      assertEquals((-2320), jmxConnectorConfig0.getMaxEntries());
  }

  @Test(timeout = 4000)
  public void test06()  throws Throwable  {
      JmxConnectorConfig jmxConnectorConfig0 = new JmxConnectorConfig();
      assertEquals(86400, jmxConnectorConfig0.getMaxEntries());
      
      jmxConnectorConfig0.setMaxEntries(0);
      int int0 = jmxConnectorConfig0.getMaxEntries();
      assertEquals(0, int0);
  }

  @Test(timeout = 4000)
  public void test07()  throws Throwable  {
      JmxConnectorConfig jmxConnectorConfig0 = new JmxConnectorConfig();
      jmxConnectorConfig0.setMaxEntries((-3591));
      int int0 = jmxConnectorConfig0.getMaxEntries();
      assertEquals((-3591), int0);
  }

  @Test(timeout = 4000)
  public void test08()  throws Throwable  {
      JmxConnectorConfig jmxConnectorConfig0 = new JmxConnectorConfig();
      jmxConnectorConfig0.setDumpTables("");
      jmxConnectorConfig0.getDumpTables();
      assertEquals(86400, jmxConnectorConfig0.getMaxEntries());
  }

  @Test(timeout = 4000)
  public void test09()  throws Throwable  {
      JmxConnectorConfig jmxConnectorConfig0 = new JmxConnectorConfig();
      JmxConnectorConfig jmxConnectorConfig1 = jmxConnectorConfig0.setDumpTables("#W)cF/C;DdtcjO");
      jmxConnectorConfig1.getDumpTables();
      assertEquals(86400, jmxConnectorConfig1.getMaxEntries());
  }

  @Test(timeout = 4000)
  public void test10()  throws Throwable  {
      JmxConnectorConfig jmxConnectorConfig0 = new JmxConnectorConfig();
      jmxConnectorConfig0.setDumpPeriod((Duration) null);
      jmxConnectorConfig0.getDumpPeriod();
      assertEquals(86400, jmxConnectorConfig0.getMaxEntries());
  }

  @Test(timeout = 4000)
  public void test11()  throws Throwable  {
      JmxConnectorConfig jmxConnectorConfig0 = new JmxConnectorConfig();
      // Undeclared exception!
      try { 
        jmxConnectorConfig0.setDumpTables((Set<String>) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("com.google.common.collect.ImmutableSet", e);
      }
  }

  @Test(timeout = 4000)
  public void test12()  throws Throwable  {
      JmxConnectorConfig jmxConnectorConfig0 = new JmxConnectorConfig();
      // Undeclared exception!
      try { 
        jmxConnectorConfig0.setDumpTables((String) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("com.google.common.base.Preconditions", e);
      }
  }

  @Test(timeout = 4000)
  public void test13()  throws Throwable  {
      JmxConnectorConfig jmxConnectorConfig0 = new JmxConnectorConfig();
      Set<String> set0 = jmxConnectorConfig0.getDumpTables();
      JmxConnectorConfig jmxConnectorConfig1 = jmxConnectorConfig0.setDumpTables(set0);
      assertEquals(86400, jmxConnectorConfig1.getMaxEntries());
  }

  @Test(timeout = 4000)
  public void test14()  throws Throwable  {
      JmxConnectorConfig jmxConnectorConfig0 = new JmxConnectorConfig();
      jmxConnectorConfig0.setMaxEntries(86400);
      assertEquals(86400, jmxConnectorConfig0.getMaxEntries());
  }

  @Test(timeout = 4000)
  public void test15()  throws Throwable  {
      JmxConnectorConfig jmxConnectorConfig0 = new JmxConnectorConfig();
      Duration duration0 = jmxConnectorConfig0.getDumpPeriod();
      JmxConnectorConfig jmxConnectorConfig1 = jmxConnectorConfig0.setDumpPeriod(duration0);
      assertEquals(86400, jmxConnectorConfig1.getMaxEntries());
      assertEquals(10.0, duration0.getValue(), 0.01);
  }

  @Test(timeout = 4000)
  public void test16()  throws Throwable  {
      JmxConnectorConfig jmxConnectorConfig0 = new JmxConnectorConfig();
      int int0 = jmxConnectorConfig0.getMaxEntries();
      assertEquals(86400, int0);
  }
}
