/*
 * This file was automatically generated by EvoSuite
 * Sat Nov 20 21:55:39 GMT 2021
 */

package com.facebook.presto.hive.metastore;

import org.junit.Test;
import static org.junit.Assert.*;
import com.facebook.presto.hive.metastore.MetastoreConfig;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class MetastoreConfig_ESTest extends MetastoreConfig_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      MetastoreConfig metastoreConfig0 = new MetastoreConfig();
      MetastoreConfig metastoreConfig1 = metastoreConfig0.setMetastoreType("");
      String string0 = metastoreConfig1.getMetastoreType();
      assertEquals("", string0);
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      MetastoreConfig metastoreConfig0 = new MetastoreConfig();
      String string0 = metastoreConfig0.getMetastoreType();
      assertEquals("thrift", string0);
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      MetastoreConfig metastoreConfig0 = new MetastoreConfig();
      MetastoreConfig metastoreConfig1 = metastoreConfig0.setMetastoreType((String) null);
      String string0 = metastoreConfig1.getMetastoreType();
      assertNull(string0);
  }
}
