/*
 * This file was automatically generated by EvoSuite
 * Sat Nov 20 19:26:25 GMT 2021
 */

package com.facebook.presto.orc.metadata;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import com.facebook.presto.orc.metadata.DwrfStripeCache;
import com.facebook.presto.orc.metadata.DwrfStripeCacheMode;
import io.airlift.slice.Slice;
import java.util.Map;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class DwrfStripeCache_ESTest extends DwrfStripeCache_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      DwrfStripeCacheMode dwrfStripeCacheMode0 = DwrfStripeCacheMode.FOOTER;
      DwrfStripeCache dwrfStripeCache0 = null;
      try {
        dwrfStripeCache0 = new DwrfStripeCache(dwrfStripeCacheMode0, (Map<Long, Slice>) null, (Map<Long, Slice>) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // indexSlices is null
         //
         verifyException("java.util.Objects", e);
      }
  }
}
