/*
 * This file was automatically generated by EvoSuite
 * Sat Nov 20 18:08:17 GMT 2021
 */

package com.facebook.presto.decoder;

import org.junit.Test;
import static org.junit.Assert.*;
import com.facebook.presto.decoder.FieldValueProvider;
import com.facebook.presto.decoder.FieldValueProviders;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class FieldValueProviders_ESTest extends FieldValueProviders_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      FieldValueProvider fieldValueProvider0 = FieldValueProviders.booleanValueProvider(true);
      assertNotNull(fieldValueProvider0);
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      FieldValueProvider fieldValueProvider0 = FieldValueProviders.longValueProvider(17L);
      assertNotNull(fieldValueProvider0);
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      FieldValueProvider fieldValueProvider0 = FieldValueProviders.nullValueProvider();
      assertNotNull(fieldValueProvider0);
  }

  @Test(timeout = 4000)
  public void test3()  throws Throwable  {
      byte[] byteArray0 = new byte[2];
      FieldValueProvider fieldValueProvider0 = FieldValueProviders.bytesValueProvider(byteArray0);
      assertNotNull(fieldValueProvider0);
  }
}
