/*
 * This file was automatically generated by EvoSuite
 * Sun Nov 21 00:31:32 GMT 2021
 */

package com.facebook.presto.kafka;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.shaded.org.mockito.Mockito.*;
import static org.evosuite.runtime.EvoAssertions.*;
import com.facebook.presto.kafka.KafkaProducerModule;
import com.facebook.presto.kafka.PlainTextKafkaProducerFactory;
import com.google.inject.Binder;
import com.google.inject.binder.AnnotatedBindingBuilder;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.evosuite.runtime.ViolatedAssumptionAnswer;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class KafkaProducerModule_ESTest extends KafkaProducerModule_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      KafkaProducerModule kafkaProducerModule0 = new KafkaProducerModule();
      Binder binder0 = mock(Binder.class, new ViolatedAssumptionAnswer());
      doReturn((AnnotatedBindingBuilder) null).when(binder0).bind(nullable(java.lang.Class.class));
      // Undeclared exception!
      try { 
        kafkaProducerModule0.configure(binder0);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("com.facebook.presto.kafka.KafkaProducerModule", e);
      }
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      KafkaProducerModule kafkaProducerModule0 = new KafkaProducerModule();
      AnnotatedBindingBuilder<PlainTextKafkaProducerFactory> annotatedBindingBuilder0 = (AnnotatedBindingBuilder<PlainTextKafkaProducerFactory>) mock(AnnotatedBindingBuilder.class, new ViolatedAssumptionAnswer());
      Binder binder0 = mock(Binder.class, new ViolatedAssumptionAnswer());
      doReturn(annotatedBindingBuilder0).when(binder0).bind(nullable(java.lang.Class.class));
      kafkaProducerModule0.configure(binder0);
  }
}
