/**
 * Scaffolding file used to store all the setups needed to run 
 * tests automatically generated by EvoSuite
 * Fri Nov 19 03:23:51 GMT 2021
 */

package com.facebook.presto.bytecode;

import org.evosuite.runtime.annotation.EvoSuiteClassExclude;
import org.junit.BeforeClass;
import org.junit.Before;
import org.junit.After;
import org.junit.AfterClass;
import org.evosuite.runtime.sandbox.Sandbox;
import org.evosuite.runtime.sandbox.Sandbox.SandboxMode;

@EvoSuiteClassExclude
public class ClassInfo_ESTest_scaffolding {

  @org.junit.Rule 
  public org.evosuite.runtime.vnet.NonFunctionalRequirementRule nfr = new org.evosuite.runtime.vnet.NonFunctionalRequirementRule();

  private static final java.util.Properties defaultProperties = (java.util.Properties) java.lang.System.getProperties().clone(); 

  private org.evosuite.runtime.thread.ThreadStopper threadStopper =  new org.evosuite.runtime.thread.ThreadStopper (org.evosuite.runtime.thread.KillSwitchHandler.getInstance(), 3000);


  @BeforeClass 
  public static void initEvoSuiteFramework() { 
    org.evosuite.runtime.RuntimeSettings.className = "com.facebook.presto.bytecode.ClassInfo"; 
    org.evosuite.runtime.GuiSupport.initialize(); 
    org.evosuite.runtime.RuntimeSettings.maxNumberOfThreads = 100; 
    org.evosuite.runtime.RuntimeSettings.maxNumberOfIterationsPerLoop = 10000; 
    org.evosuite.runtime.RuntimeSettings.mockSystemIn = true; 
    org.evosuite.runtime.RuntimeSettings.sandboxMode = org.evosuite.runtime.sandbox.Sandbox.SandboxMode.RECOMMENDED; 
    org.evosuite.runtime.sandbox.Sandbox.initializeSecurityManagerForSUT(); 
    org.evosuite.runtime.classhandling.JDKClassResetter.init();
    setSystemProperties();
    initializeClasses();
    org.evosuite.runtime.Runtime.getInstance().resetRuntime(); 
  } 

  @AfterClass 
  public static void clearEvoSuiteFramework(){ 
    Sandbox.resetDefaultSecurityManager(); 
    java.lang.System.setProperties((java.util.Properties) defaultProperties.clone()); 
  } 

  @Before 
  public void initTestCase(){ 
    threadStopper.storeCurrentThreads();
    threadStopper.startRecordingTime();
    org.evosuite.runtime.jvm.ShutdownHookHandler.getInstance().initHandler(); 
    org.evosuite.runtime.sandbox.Sandbox.goingToExecuteSUTCode(); 
    setSystemProperties(); 
    org.evosuite.runtime.GuiSupport.setHeadless(); 
    org.evosuite.runtime.Runtime.getInstance().resetRuntime(); 
    org.evosuite.runtime.agent.InstrumentingAgent.activate(); 
  } 

  @After 
  public void doneWithTestCase(){ 
    threadStopper.killAndJoinClientThreads();
    org.evosuite.runtime.jvm.ShutdownHookHandler.getInstance().safeExecuteAddedHooks(); 
    org.evosuite.runtime.classhandling.JDKClassResetter.reset(); 
    resetClasses(); 
    org.evosuite.runtime.sandbox.Sandbox.doneWithExecutingSUTCode(); 
    org.evosuite.runtime.agent.InstrumentingAgent.deactivate(); 
    org.evosuite.runtime.GuiSupport.restoreHeadlessMode(); 
  } 

  public static void setSystemProperties() {
 
    java.lang.System.setProperties((java.util.Properties) defaultProperties.clone()); 
    java.lang.System.setProperty("file.encoding", "UTF-8"); 
    java.lang.System.setProperty("java.awt.headless", "true"); 
    java.lang.System.setProperty("java.io.tmpdir", "/tmp"); 
    java.lang.System.setProperty("user.dir", "/mnt/c/Users/Helen/Documents/DataScience18668/GroupProject/project/presto/presto-bytecode"); 
    java.lang.System.setProperty("user.home", "/home/helen"); 
    java.lang.System.setProperty("user.language", "en"); 
    java.lang.System.setProperty("user.name", "helen"); 
    java.lang.System.setProperty("user.timezone", "America/Los_Angeles"); 
  }

  private static void initializeClasses() {
    org.evosuite.runtime.classhandling.ClassStateSupport.initializeClasses(ClassInfo_ESTest_scaffolding.class.getClassLoader() ,
      "org.objectweb.asm.tree.FieldInsnNode",
      "com.facebook.presto.bytecode.ClassInfoLoader",
      "com.google.common.collect.ImmutableList$SubList",
      "org.objectweb.asm.tree.analysis.AnalyzerException",
      "com.google.common.collect.Lists$RandomAccessPartition",
      "com.google.common.collect.PeekingIterator",
      "com.google.common.collect.RegularImmutableList",
      "com.google.common.collect.FluentIterable",
      "com.google.common.base.Optional",
      "com.google.common.collect.Lists$TransformingRandomAccessList",
      "com.google.common.collect.RegularImmutableMap$KeySet",
      "com.google.common.collect.Iterators$ArrayItr",
      "com.google.common.collect.RegularImmutableMap",
      "org.objectweb.asm.tree.RecordComponentNode",
      "com.google.common.collect.Iterators$10",
      "org.objectweb.asm.tree.Util",
      "com.google.common.collect.AbstractMapEntry",
      "com.google.common.collect.ImmutableMap$IteratorBasedImmutableMap",
      "org.objectweb.asm.tree.VarInsnNode",
      "org.objectweb.asm.MethodWriter",
      "org.objectweb.asm.tree.ClassNode",
      "com.google.common.base.Present",
      "org.objectweb.asm.util.Textifier",
      "org.objectweb.asm.util.TraceMethodVisitor",
      "org.objectweb.asm.tree.AnnotationNode",
      "org.objectweb.asm.AnnotationVisitor",
      "org.objectweb.asm.tree.MethodInsnNode",
      "com.google.common.collect.Iterables",
      "org.objectweb.asm.tree.LineNumberNode",
      "com.google.common.collect.ImmutableAsList",
      "com.google.common.collect.ImmutableMapEntrySet$RegularEntrySet",
      "org.objectweb.asm.tree.IntInsnNode",
      "com.google.common.collect.RegularImmutableAsList",
      "org.objectweb.asm.util.CheckMethodAdapter$Method",
      "com.google.common.collect.ImmutableMapEntrySet",
      "com.google.common.base.Strings",
      "org.objectweb.asm.Context",
      "com.google.common.collect.Lists$Partition",
      "com.google.common.collect.Lists",
      "com.google.common.collect.UnmodifiableListIterator",
      "org.objectweb.asm.Attribute",
      "org.objectweb.asm.tree.JumpInsnNode",
      "com.google.common.collect.Lists$TransformingSequentialList",
      "org.objectweb.asm.Opcodes",
      "com.google.common.base.Absent",
      "com.google.common.collect.ObjectArrays",
      "org.objectweb.asm.tree.analysis.BasicVerifier",
      "org.objectweb.asm.tree.InsnList",
      "com.google.common.collect.AbstractIterator",
      "org.objectweb.asm.tree.ModuleNode",
      "com.google.common.collect.ImmutableList$1",
      "org.objectweb.asm.Handle",
      "com.google.common.collect.ImmutableMap$MapViewOfValuesAsSingletonSets",
      "org.objectweb.asm.util.Printer",
      "org.objectweb.asm.util.CheckMethodAdapter$1",
      "com.google.common.collect.ImmutableMapEntry$NonTerminalImmutableMapEntry",
      "com.google.common.base.Preconditions",
      "com.google.common.collect.UnmodifiableIterator",
      "org.objectweb.asm.tree.LookupSwitchInsnNode",
      "org.objectweb.asm.tree.analysis.BasicInterpreter",
      "com.facebook.presto.bytecode.ParameterizedType",
      "org.objectweb.asm.util.CheckMethodAdapter",
      "com.google.common.collect.ImmutableEntry",
      "org.objectweb.asm.tree.TableSwitchInsnNode",
      "org.objectweb.asm.MethodVisitor",
      "org.objectweb.asm.tree.IincInsnNode",
      "com.google.common.collect.ImmutableCollection",
      "org.objectweb.asm.Type",
      "org.objectweb.asm.tree.MultiANewArrayInsnNode",
      "org.objectweb.asm.tree.InnerClassNode",
      "com.google.common.collect.Lists$RandomAccessListWrapper",
      "com.facebook.presto.bytecode.ClassInfo",
      "org.objectweb.asm.util.CheckAnnotationAdapter",
      "org.objectweb.asm.tree.TypeAnnotationNode",
      "com.google.common.collect.ImmutableList$ReverseImmutableList",
      "org.objectweb.asm.tree.LocalVariableAnnotationNode",
      "org.objectweb.asm.util.CheckClassAdapter$1",
      "org.objectweb.asm.ClassVisitor",
      "com.google.common.collect.SingletonImmutableList",
      "org.objectweb.asm.tree.analysis.Interpreter",
      "com.google.common.collect.ImmutableCollection$Builder",
      "com.google.common.collect.Iterators$6",
      "com.google.common.collect.BiMap",
      "com.google.common.collect.IndexedImmutableSet",
      "com.google.common.base.Function",
      "com.google.common.collect.ImmutableSet",
      "com.google.common.collect.Iterators$9",
      "com.google.common.collect.Lists$AbstractListWrapper",
      "com.google.common.collect.ImmutableMap",
      "com.google.common.collect.ImmutableMapEntry",
      "org.objectweb.asm.util.CheckFieldAdapter",
      "com.google.common.collect.AbstractIndexedListIterator",
      "org.objectweb.asm.util.CheckRecordComponentAdapter",
      "com.google.common.collect.Iterators$1",
      "com.google.common.collect.Iterators$4",
      "com.google.common.collect.Iterators$5",
      "com.facebook.presto.bytecode.ClassDefinition",
      "org.objectweb.asm.ClassReader",
      "org.objectweb.asm.tree.TryCatchBlockNode",
      "com.google.common.collect.Lists$StringAsImmutableList",
      "org.objectweb.asm.tree.InvokeDynamicInsnNode",
      "org.objectweb.asm.tree.FrameNode",
      "com.google.common.collect.Lists$2",
      "org.objectweb.asm.tree.FieldNode",
      "org.objectweb.asm.ConstantDynamic",
      "com.google.common.collect.ImmutableMap$1",
      "com.google.common.collect.ImmutableList$Builder",
      "com.google.common.collect.Lists$1",
      "com.google.common.collect.Iterables$5",
      "org.objectweb.asm.FieldVisitor",
      "org.objectweb.asm.Label",
      "com.google.common.collect.Iterators",
      "com.google.common.collect.ImmutableBiMap",
      "org.objectweb.asm.tree.MethodNode",
      "com.google.common.collect.ImmutableList",
      "org.objectweb.asm.tree.TypeInsnNode",
      "com.google.common.collect.FluentIterable$1",
      "com.google.common.collect.FluentIterable$2",
      "com.google.common.collect.ImmutableBiMapFauxverideShim",
      "com.google.common.collect.FluentIterable$3",
      "org.objectweb.asm.ModuleVisitor",
      "org.objectweb.asm.RecordComponentVisitor",
      "org.objectweb.asm.util.CheckModuleAdapter",
      "org.objectweb.asm.tree.UnsupportedClassVersionException",
      "org.objectweb.asm.tree.LabelNode",
      "org.objectweb.asm.util.CheckClassAdapter",
      "com.google.common.collect.ImmutableMap$Builder",
      "com.google.common.collect.TransformedIterator",
      "org.objectweb.asm.tree.LdcInsnNode",
      "org.objectweb.asm.TypePath",
      "org.objectweb.asm.tree.analysis.SimpleVerifier",
      "org.objectweb.asm.tree.AbstractInsnNode",
      "com.google.common.collect.Iterators$MergingIterator",
      "com.google.common.collect.RegularImmutableMap$Values",
      "org.objectweb.asm.tree.InsnNode"
    );
  } 

  private static void resetClasses() {
    org.evosuite.runtime.classhandling.ClassResetter.getInstance().setClassLoader(ClassInfo_ESTest_scaffolding.class.getClassLoader()); 

    org.evosuite.runtime.classhandling.ClassStateSupport.resetClasses(
      "com.facebook.presto.bytecode.ClassInfo",
      "com.google.common.collect.ImmutableCollection",
      "com.google.common.collect.ImmutableList",
      "com.google.common.collect.RegularImmutableList",
      "org.objectweb.asm.ClassVisitor",
      "org.objectweb.asm.tree.ClassNode",
      "org.objectweb.asm.tree.Util",
      "com.facebook.presto.bytecode.ParameterizedType",
      "com.google.common.base.Preconditions",
      "com.google.common.collect.Iterables",
      "com.google.common.collect.FluentIterable",
      "com.google.common.collect.Iterables$5",
      "com.google.common.base.Optional",
      "com.google.common.base.Absent",
      "com.facebook.presto.bytecode.ClassInfoLoader",
      "com.google.common.collect.ImmutableMap",
      "com.google.common.collect.ImmutableMap$Builder",
      "com.google.common.collect.RegularImmutableMap",
      "com.google.common.collect.ObjectArrays",
      "com.google.common.collect.SingletonImmutableList",
      "com.google.common.collect.ImmutableCollection$Builder",
      "com.google.common.collect.ImmutableList$Builder",
      "com.google.common.collect.Iterators",
      "com.google.common.collect.UnmodifiableIterator",
      "com.google.common.collect.Iterators$9",
      "org.objectweb.asm.ClassReader",
      "org.objectweb.asm.util.CheckClassAdapter",
      "org.objectweb.asm.Context",
      "org.objectweb.asm.MethodVisitor",
      "org.objectweb.asm.util.CheckMethodAdapter$Method",
      "org.objectweb.asm.util.CheckMethodAdapter",
      "org.objectweb.asm.tree.InnerClassNode",
      "org.objectweb.asm.FieldVisitor",
      "org.objectweb.asm.util.CheckFieldAdapter",
      "org.objectweb.asm.tree.FieldNode",
      "org.objectweb.asm.tree.MethodNode",
      "org.objectweb.asm.tree.InsnList",
      "org.objectweb.asm.tree.AbstractInsnNode",
      "org.objectweb.asm.tree.VarInsnNode",
      "org.objectweb.asm.tree.MethodInsnNode",
      "org.objectweb.asm.tree.InsnNode",
      "org.objectweb.asm.tree.FieldInsnNode",
      "org.objectweb.asm.Label",
      "org.objectweb.asm.tree.TypeInsnNode",
      "org.objectweb.asm.tree.JumpInsnNode",
      "org.objectweb.asm.tree.LabelNode",
      "org.objectweb.asm.tree.LdcInsnNode",
      "org.objectweb.asm.Opcodes",
      "org.objectweb.asm.tree.FrameNode",
      "org.objectweb.asm.tree.IntInsnNode",
      "org.objectweb.asm.tree.IincInsnNode",
      "org.objectweb.asm.AnnotationVisitor",
      "org.objectweb.asm.util.CheckAnnotationAdapter",
      "org.objectweb.asm.tree.AnnotationNode",
      "org.objectweb.asm.tree.TryCatchBlockNode",
      "org.objectweb.asm.Type",
      "org.objectweb.asm.TypePath",
      "org.objectweb.asm.tree.TypeAnnotationNode",
      "com.google.common.base.Strings",
      "com.google.common.collect.UnmodifiableListIterator",
      "com.google.common.collect.AbstractIndexedListIterator",
      "com.google.common.collect.Iterators$ArrayItr",
      "com.google.common.collect.ImmutableBiMapFauxverideShim",
      "com.google.common.collect.ImmutableBiMap",
      "com.google.common.collect.SingletonImmutableBiMap",
      "com.google.common.collect.CollectPreconditions",
      "com.google.common.collect.TransformedIterator",
      "com.google.common.collect.Iterators$6",
      "org.objectweb.asm.Handle",
      "org.objectweb.asm.tree.InvokeDynamicInsnNode",
      "com.google.common.collect.Lists"
    );
  }
}
