/*
 * This file was automatically generated by EvoSuite
 * Thu Nov 18 22:01:42 GMT 2021
 */

package com.facebook.presto.bytecode;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import com.facebook.presto.bytecode.Binding;
import com.facebook.presto.bytecode.StaticTypeBytecodeExpression;
import java.lang.invoke.MethodType;
import java.lang.reflect.Method;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class StaticTypeBytecodeExpression_ESTest extends StaticTypeBytecodeExpression_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      Binding binding0 = new Binding(0L, (MethodType) null);
      Class<String> class0 = String.class;
      StaticTypeBytecodeExpression staticTypeBytecodeExpression0 = null;
      try {
        staticTypeBytecodeExpression0 = new StaticTypeBytecodeExpression(binding0, (Method) null, class0, "u?b9QnjEUWmvV", class0);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // bootstrapMethod is null
         //
         verifyException("java.util.Objects", e);
      }
  }
}
