/*
 * This file was automatically generated by EvoSuite
 * Mon Nov 22 19:16:15 GMT 2021
 */

package com.facebook.presto.connector.thrift.location;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import com.facebook.drift.client.address.AddressSelector;
import com.facebook.drift.client.address.SimpleAddressSelector;
import com.facebook.presto.connector.thrift.location.ExtendedSimpleAddressSelector;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class ExtendedSimpleAddressSelector_ESTest extends ExtendedSimpleAddressSelector_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      ExtendedSimpleAddressSelector extendedSimpleAddressSelector0 = null;
      try {
        extendedSimpleAddressSelector0 = new ExtendedSimpleAddressSelector((AddressSelector<SimpleAddressSelector.SimpleAddress>) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // delegate is null
         //
         verifyException("java.util.Objects", e);
      }
  }
}
