/*
 * This file was automatically generated by EvoSuite
 * Sun Nov 21 07:45:34 GMT 2021
 */

package com.facebook.presto.elasticsearch;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import com.facebook.presto.common.predicate.TupleDomain;
import com.facebook.presto.elasticsearch.ElasticsearchColumnHandle;
import com.facebook.presto.elasticsearch.ElasticsearchQueryBuilder;
import com.facebook.presto.spi.ConnectorSession;
import java.util.Optional;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class ElasticsearchQueryBuilder_ESTest extends ElasticsearchQueryBuilder_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      // Undeclared exception!
      try { 
        ElasticsearchQueryBuilder.buildSearchQuery((ConnectorSession) null, (TupleDomain<ElasticsearchColumnHandle>) null, (Optional<String>) null);
        fail("Expecting exception: NoClassDefFoundError");
      
      } catch(NoClassDefFoundError e) {
         //
         // Could not initialize class org.elasticsearch.index.query.BoolQueryBuilder
         //
         verifyException("com.facebook.presto.elasticsearch.ElasticsearchQueryBuilder", e);
      }
  }
}
