/*
 * This file was automatically generated by EvoSuite
 * Sun Nov 21 02:20:00 GMT 2021
 */

package com.facebook.presto.cassandra;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.shaded.org.mockito.Mockito.*;
import static org.evosuite.runtime.EvoAssertions.*;
import com.facebook.airlift.bootstrap.LifeCycleManager;
import com.facebook.presto.cassandra.CassandraConnector;
import com.facebook.presto.cassandra.CassandraMetadata;
import com.facebook.presto.cassandra.CassandraPageSinkProvider;
import com.facebook.presto.cassandra.CassandraRecordSetProvider;
import com.facebook.presto.cassandra.CassandraSessionProperties;
import com.facebook.presto.cassandra.CassandraSplitManager;
import java.util.List;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.evosuite.runtime.ViolatedAssumptionAnswer;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class CassandraConnector_ESTest extends CassandraConnector_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      LifeCycleManager lifeCycleManager0 = mock(LifeCycleManager.class, new ViolatedAssumptionAnswer());
      CassandraMetadata cassandraMetadata0 = mock(CassandraMetadata.class, new ViolatedAssumptionAnswer());
      CassandraSplitManager cassandraSplitManager0 = mock(CassandraSplitManager.class, new ViolatedAssumptionAnswer());
      CassandraRecordSetProvider cassandraRecordSetProvider0 = mock(CassandraRecordSetProvider.class, new ViolatedAssumptionAnswer());
      CassandraPageSinkProvider cassandraPageSinkProvider0 = mock(CassandraPageSinkProvider.class, new ViolatedAssumptionAnswer());
      CassandraSessionProperties cassandraSessionProperties0 = mock(CassandraSessionProperties.class, new ViolatedAssumptionAnswer());
      doReturn((List) null).when(cassandraSessionProperties0).getSessionProperties();
      CassandraConnector cassandraConnector0 = null;
      try {
        cassandraConnector0 = new CassandraConnector(lifeCycleManager0, cassandraMetadata0, cassandraSplitManager0, cassandraRecordSetProvider0, cassandraPageSinkProvider0, cassandraSessionProperties0);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // sessionProperties is null
         //
         verifyException("java.util.Objects", e);
      }
  }
}
