/*
 * This file was automatically generated by EvoSuite
 * Sun Nov 21 02:05:30 GMT 2021
 */

package com.facebook.presto.cassandra;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.shaded.org.mockito.Mockito.*;
import static org.evosuite.runtime.EvoAssertions.*;
import com.facebook.presto.cassandra.CassandraPartitionManager;
import com.facebook.presto.cassandra.CassandraSession;
import com.facebook.presto.common.predicate.TupleDomain;
import com.facebook.presto.spi.ColumnHandle;
import com.facebook.presto.spi.ConnectorTableHandle;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.evosuite.runtime.ViolatedAssumptionAnswer;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class CassandraPartitionManager_ESTest extends CassandraPartitionManager_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      CassandraSession cassandraSession0 = mock(CassandraSession.class, new ViolatedAssumptionAnswer());
      CassandraPartitionManager cassandraPartitionManager0 = new CassandraPartitionManager(cassandraSession0);
      TupleDomain<ColumnHandle> tupleDomain0 = (TupleDomain<ColumnHandle>) mock(TupleDomain.class, new ViolatedAssumptionAnswer());
      // Undeclared exception!
      try { 
        cassandraPartitionManager0.getPartitions((ConnectorTableHandle) null, tupleDomain0);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("com.facebook.presto.cassandra.CassandraPartitionManager", e);
      }
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      CassandraSession cassandraSession0 = mock(CassandraSession.class, new ViolatedAssumptionAnswer());
      CassandraPartitionManager cassandraPartitionManager0 = new CassandraPartitionManager(cassandraSession0);
      ConnectorTableHandle connectorTableHandle0 = mock(ConnectorTableHandle.class, new ViolatedAssumptionAnswer());
      TupleDomain<ColumnHandle> tupleDomain0 = (TupleDomain<ColumnHandle>) mock(TupleDomain.class, new ViolatedAssumptionAnswer());
      // Undeclared exception!
      try { 
        cassandraPartitionManager0.getPartitions(connectorTableHandle0, tupleDomain0);
        fail("Expecting exception: ClassCastException");
      
      } catch(ClassCastException e) {
         //
         // com.facebook.presto.spi.ConnectorTableHandle$MockitoMock$1964860011 cannot be cast to com.facebook.presto.cassandra.CassandraTableHandle
         //
         verifyException("com.facebook.presto.cassandra.CassandraPartitionManager", e);
      }
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      CassandraPartitionManager cassandraPartitionManager0 = null;
      try {
        cassandraPartitionManager0 = new CassandraPartitionManager((CassandraSession) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // cassandraSession is null
         //
         verifyException("java.util.Objects", e);
      }
  }
}
