/**
 * Scaffolding file used to store all the setups needed to run 
 * tests automatically generated by EvoSuite
 * Mon Nov 22 19:12:10 GMT 2021
 */

package com.facebook.presto.connector.thrift.util;

import org.evosuite.runtime.annotation.EvoSuiteClassExclude;
import org.junit.BeforeClass;
import org.junit.Before;
import org.junit.After;
import org.junit.AfterClass;
import org.evosuite.runtime.sandbox.Sandbox;
import org.evosuite.runtime.sandbox.Sandbox.SandboxMode;

@EvoSuiteClassExclude
public class ThriftExceptions_ESTest_scaffolding {

  @org.junit.Rule 
  public org.evosuite.runtime.vnet.NonFunctionalRequirementRule nfr = new org.evosuite.runtime.vnet.NonFunctionalRequirementRule();

  private static final java.util.Properties defaultProperties = (java.util.Properties) java.lang.System.getProperties().clone(); 

  private org.evosuite.runtime.thread.ThreadStopper threadStopper =  new org.evosuite.runtime.thread.ThreadStopper (org.evosuite.runtime.thread.KillSwitchHandler.getInstance(), 3000);


  @BeforeClass 
  public static void initEvoSuiteFramework() { 
    org.evosuite.runtime.RuntimeSettings.className = "com.facebook.presto.connector.thrift.util.ThriftExceptions"; 
    org.evosuite.runtime.GuiSupport.initialize(); 
    org.evosuite.runtime.RuntimeSettings.maxNumberOfThreads = 100; 
    org.evosuite.runtime.RuntimeSettings.maxNumberOfIterationsPerLoop = 10000; 
    org.evosuite.runtime.RuntimeSettings.mockSystemIn = true; 
    org.evosuite.runtime.RuntimeSettings.sandboxMode = org.evosuite.runtime.sandbox.Sandbox.SandboxMode.RECOMMENDED; 
    org.evosuite.runtime.sandbox.Sandbox.initializeSecurityManagerForSUT(); 
    org.evosuite.runtime.classhandling.JDKClassResetter.init();
    setSystemProperties();
    initializeClasses();
    org.evosuite.runtime.Runtime.getInstance().resetRuntime(); 
  } 

  @AfterClass 
  public static void clearEvoSuiteFramework(){ 
    Sandbox.resetDefaultSecurityManager(); 
    java.lang.System.setProperties((java.util.Properties) defaultProperties.clone()); 
  } 

  @Before 
  public void initTestCase(){ 
    threadStopper.storeCurrentThreads();
    threadStopper.startRecordingTime();
    org.evosuite.runtime.jvm.ShutdownHookHandler.getInstance().initHandler(); 
    org.evosuite.runtime.sandbox.Sandbox.goingToExecuteSUTCode(); 
    setSystemProperties(); 
    org.evosuite.runtime.GuiSupport.setHeadless(); 
    org.evosuite.runtime.Runtime.getInstance().resetRuntime(); 
    org.evosuite.runtime.agent.InstrumentingAgent.activate(); 
  } 

  @After 
  public void doneWithTestCase(){ 
    threadStopper.killAndJoinClientThreads();
    org.evosuite.runtime.jvm.ShutdownHookHandler.getInstance().safeExecuteAddedHooks(); 
    org.evosuite.runtime.classhandling.JDKClassResetter.reset(); 
    resetClasses(); 
    org.evosuite.runtime.sandbox.Sandbox.doneWithExecutingSUTCode(); 
    org.evosuite.runtime.agent.InstrumentingAgent.deactivate(); 
    org.evosuite.runtime.GuiSupport.restoreHeadlessMode(); 
  } 

  public static void setSystemProperties() {
 
    java.lang.System.setProperties((java.util.Properties) defaultProperties.clone()); 
    java.lang.System.setProperty("file.encoding", "UTF-8"); 
    java.lang.System.setProperty("java.awt.headless", "true"); 
    java.lang.System.setProperty("java.io.tmpdir", "/tmp"); 
    java.lang.System.setProperty("user.dir", "/mnt/c/Users/Helen/Documents/DataScience18668/GroupProject/project/presto/presto-thrift-connector"); 
    java.lang.System.setProperty("user.home", "/home/helen"); 
    java.lang.System.setProperty("user.language", "en"); 
    java.lang.System.setProperty("user.name", "helen"); 
    java.lang.System.setProperty("user.timezone", "America/Los_Angeles"); 
  }

  private static void initializeClasses() {
    org.evosuite.runtime.classhandling.ClassStateSupport.initializeClasses(ThriftExceptions_ESTest_scaffolding.class.getClassLoader() ,
      "com.google.common.util.concurrent.AbstractFuture$AtomicHelper",
      "com.google.common.util.concurrent.AbstractCatchingFuture$CatchingFuture",
      "com.google.common.util.concurrent.MoreExecutors",
      "com.google.common.util.concurrent.ListenableFuture",
      "com.google.common.util.concurrent.MoreExecutors$DirectExecutor",
      "com.facebook.presto.spi.ErrorCode",
      "com.facebook.presto.connector.thrift.ThriftErrorCode",
      "com.google.common.util.concurrent.AbstractFuture$TrustedFuture",
      "com.google.common.util.concurrent.CheckedFuture",
      "com.google.common.collect.ImmutableCollection",
      "com.google.common.util.concurrent.ExecutionError",
      "com.facebook.presto.spi.PrestoException",
      "com.facebook.presto.spi.ErrorType",
      "com.google.common.util.concurrent.AbstractCatchingFuture$AsyncCatchingFuture",
      "com.google.common.util.concurrent.GwtFluentFutureCatchingSpecialization",
      "com.google.common.util.concurrent.ForwardingFluentFuture",
      "com.google.common.util.concurrent.AbstractFuture$SynchronizedHelper",
      "com.google.common.util.concurrent.GwtFuturesCatchingSpecialization",
      "com.google.common.collect.ImmutableList",
      "com.google.common.util.concurrent.AbstractFuture$SafeAtomicHelper",
      "com.google.common.util.concurrent.UncheckedExecutionException",
      "com.google.common.util.concurrent.AbstractFuture$UnsafeAtomicHelper",
      "com.google.common.util.concurrent.AbstractFuture$Waiter",
      "com.google.common.util.concurrent.ListeningScheduledExecutorService",
      "com.google.common.util.concurrent.AbstractCatchingFuture",
      "com.facebook.presto.connector.thrift.util.ThriftExceptions",
      "com.google.common.util.concurrent.Futures",
      "com.google.common.util.concurrent.AbstractFuture$UnsafeAtomicHelper$1",
      "com.google.common.util.concurrent.AbstractFuture$Listener",
      "com.facebook.presto.spi.StandardErrorCode",
      "com.facebook.presto.spi.ErrorCodeSupplier",
      "com.google.common.util.concurrent.AsyncFunction",
      "com.google.common.base.Preconditions",
      "com.google.common.util.concurrent.AbstractFuture",
      "com.google.common.util.concurrent.ListeningExecutorService",
      "com.google.common.util.concurrent.FluentFuture"
    );
  } 

  private static void resetClasses() {
    org.evosuite.runtime.classhandling.ClassResetter.getInstance().setClassLoader(ThriftExceptions_ESTest_scaffolding.class.getClassLoader()); 

    org.evosuite.runtime.classhandling.ClassStateSupport.resetClasses(
      "com.facebook.presto.connector.thrift.util.ThriftExceptions",
      "com.facebook.presto.spi.ErrorType",
      "com.facebook.presto.spi.ErrorCode",
      "com.facebook.presto.connector.thrift.ThriftErrorCode",
      "com.facebook.presto.spi.StandardErrorCode",
      "com.google.common.util.concurrent.MoreExecutors$DirectExecutor",
      "com.facebook.presto.spi.PrestoException",
      "com.google.common.util.concurrent.MoreExecutors",
      "com.google.common.util.concurrent.GwtFuturesCatchingSpecialization",
      "com.google.common.util.concurrent.Futures",
      "com.google.common.util.concurrent.GwtFluentFutureCatchingSpecialization",
      "com.google.common.util.concurrent.FluentFuture",
      "com.google.common.util.concurrent.AbstractFuture$AtomicHelper",
      "com.google.common.util.concurrent.AbstractFuture$UnsafeAtomicHelper$1",
      "com.google.common.util.concurrent.AbstractFuture$UnsafeAtomicHelper",
      "com.google.common.util.concurrent.AbstractFuture",
      "com.google.common.util.concurrent.AbstractFuture$TrustedFuture",
      "com.google.common.util.concurrent.AbstractCatchingFuture",
      "com.google.common.util.concurrent.AbstractCatchingFuture$AsyncCatchingFuture",
      "com.google.common.base.Preconditions"
    );
  }
}
