/*
 * This file was automatically generated by EvoSuite
 * Mon Nov 22 09:26:50 GMT 2021
 */

package com.facebook.presto.tpcds;

import org.junit.Test;
import static org.junit.Assert.*;
import com.facebook.presto.spi.ColumnHandle;
import com.facebook.presto.spi.ConnectorSplit;
import com.facebook.presto.spi.ConnectorTableHandle;
import com.facebook.presto.spi.ConnectorTableLayoutHandle;
import com.facebook.presto.spi.connector.ConnectorPartitioningHandle;
import com.facebook.presto.spi.connector.ConnectorTransactionHandle;
import com.facebook.presto.tpcds.TpcdsHandleResolver;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class TpcdsHandleResolver_ESTest extends TpcdsHandleResolver_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      TpcdsHandleResolver tpcdsHandleResolver0 = new TpcdsHandleResolver();
      Class<? extends ConnectorTableHandle> class0 = tpcdsHandleResolver0.getTableHandleClass();
      assertFalse(class0.isInterface());
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      TpcdsHandleResolver tpcdsHandleResolver0 = new TpcdsHandleResolver();
      Class<? extends ConnectorTransactionHandle> class0 = tpcdsHandleResolver0.getTransactionHandleClass();
      assertFalse(class0.isAnnotation());
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      TpcdsHandleResolver tpcdsHandleResolver0 = new TpcdsHandleResolver();
      Class<? extends ConnectorSplit> class0 = tpcdsHandleResolver0.getSplitClass();
      assertEquals("class com.facebook.presto.tpcds.TpcdsSplit", class0.toString());
  }

  @Test(timeout = 4000)
  public void test3()  throws Throwable  {
      TpcdsHandleResolver tpcdsHandleResolver0 = new TpcdsHandleResolver();
      Class<? extends ColumnHandle> class0 = tpcdsHandleResolver0.getColumnHandleClass();
      assertEquals("class com.facebook.presto.tpcds.TpcdsColumnHandle", class0.toString());
  }

  @Test(timeout = 4000)
  public void test4()  throws Throwable  {
      TpcdsHandleResolver tpcdsHandleResolver0 = new TpcdsHandleResolver();
      Class<? extends ConnectorPartitioningHandle> class0 = tpcdsHandleResolver0.getPartitioningHandleClass();
      assertFalse(class0.isPrimitive());
  }

  @Test(timeout = 4000)
  public void test5()  throws Throwable  {
      TpcdsHandleResolver tpcdsHandleResolver0 = new TpcdsHandleResolver();
      Class<? extends ConnectorTableLayoutHandle> class0 = tpcdsHandleResolver0.getTableLayoutHandleClass();
      assertFalse(class0.isInterface());
  }
}
