/**
 * Scaffolding file used to store all the setups needed to run 
 * tests automatically generated by EvoSuite
 * Sun Nov 21 08:40:49 GMT 2021
 */

package com.facebook.presto.druid.zip;

import org.evosuite.runtime.annotation.EvoSuiteClassExclude;
import org.junit.BeforeClass;
import org.junit.Before;
import org.junit.After;
import org.junit.AfterClass;
import org.evosuite.runtime.sandbox.Sandbox;
import org.evosuite.runtime.sandbox.Sandbox.SandboxMode;

import static org.evosuite.shaded.org.mockito.Mockito.*;
@EvoSuiteClassExclude
public class CentralDirectoryFileHeader_ESTest_scaffolding {

  @org.junit.Rule 
  public org.evosuite.runtime.vnet.NonFunctionalRequirementRule nfr = new org.evosuite.runtime.vnet.NonFunctionalRequirementRule();

  private static final java.util.Properties defaultProperties = (java.util.Properties) java.lang.System.getProperties().clone(); 

  private org.evosuite.runtime.thread.ThreadStopper threadStopper =  new org.evosuite.runtime.thread.ThreadStopper (org.evosuite.runtime.thread.KillSwitchHandler.getInstance(), 3000);


  @BeforeClass 
  public static void initEvoSuiteFramework() { 
    org.evosuite.runtime.RuntimeSettings.className = "com.facebook.presto.druid.zip.CentralDirectoryFileHeader"; 
    org.evosuite.runtime.GuiSupport.initialize(); 
    org.evosuite.runtime.RuntimeSettings.maxNumberOfThreads = 100; 
    org.evosuite.runtime.RuntimeSettings.maxNumberOfIterationsPerLoop = 10000; 
    org.evosuite.runtime.RuntimeSettings.mockSystemIn = true; 
    org.evosuite.runtime.RuntimeSettings.sandboxMode = org.evosuite.runtime.sandbox.Sandbox.SandboxMode.RECOMMENDED; 
    org.evosuite.runtime.sandbox.Sandbox.initializeSecurityManagerForSUT(); 
    org.evosuite.runtime.classhandling.JDKClassResetter.init();
    setSystemProperties();
    initializeClasses();
    org.evosuite.runtime.Runtime.getInstance().resetRuntime(); 
    try { initMocksToAvoidTimeoutsInTheTests(); } catch(ClassNotFoundException e) {} 
  } 

  @AfterClass 
  public static void clearEvoSuiteFramework(){ 
    Sandbox.resetDefaultSecurityManager(); 
    java.lang.System.setProperties((java.util.Properties) defaultProperties.clone()); 
  } 

  @Before 
  public void initTestCase(){ 
    threadStopper.storeCurrentThreads();
    threadStopper.startRecordingTime();
    org.evosuite.runtime.jvm.ShutdownHookHandler.getInstance().initHandler(); 
    org.evosuite.runtime.sandbox.Sandbox.goingToExecuteSUTCode(); 
    setSystemProperties(); 
    org.evosuite.runtime.GuiSupport.setHeadless(); 
    org.evosuite.runtime.Runtime.getInstance().resetRuntime(); 
    org.evosuite.runtime.agent.InstrumentingAgent.activate(); 
  } 

  @After 
  public void doneWithTestCase(){ 
    threadStopper.killAndJoinClientThreads();
    org.evosuite.runtime.jvm.ShutdownHookHandler.getInstance().safeExecuteAddedHooks(); 
    org.evosuite.runtime.classhandling.JDKClassResetter.reset(); 
    resetClasses(); 
    org.evosuite.runtime.sandbox.Sandbox.doneWithExecutingSUTCode(); 
    org.evosuite.runtime.agent.InstrumentingAgent.deactivate(); 
    org.evosuite.runtime.GuiSupport.restoreHeadlessMode(); 
  } 

  public static void setSystemProperties() {
 
    java.lang.System.setProperties((java.util.Properties) defaultProperties.clone()); 
    java.lang.System.setProperty("file.encoding", "UTF-8"); 
    java.lang.System.setProperty("java.awt.headless", "true"); 
    java.lang.System.setProperty("java.io.tmpdir", "/tmp"); 
    java.lang.System.setProperty("user.dir", "/mnt/c/Users/Helen/Documents/DataScience18668/GroupProject/project/presto/presto-druid"); 
    java.lang.System.setProperty("user.home", "/home/helen"); 
    java.lang.System.setProperty("user.language", "en"); 
    java.lang.System.setProperty("user.name", "helen"); 
    java.lang.System.setProperty("user.timezone", "America/Los_Angeles"); 
  }

  private static void initializeClasses() {
    org.evosuite.runtime.classhandling.ClassStateSupport.initializeClasses(CentralDirectoryFileHeader_ESTest_scaffolding.class.getClassLoader() ,
      "com.facebook.presto.druid.zip.ExtraDataList",
      "com.facebook.presto.druid.DataInputSourceId",
      "com.facebook.presto.spi.ErrorCode",
      "com.facebook.presto.druid.DruidErrorCode",
      "com.facebook.presto.spi.PrestoException",
      "com.facebook.presto.druid.DataInputSource",
      "com.facebook.presto.druid.zip.ZipFileEntry$Compression",
      "com.facebook.presto.spi.ErrorType",
      "com.facebook.presto.druid.zip.ExtraData",
      "com.facebook.drift.annotations.ThriftStruct",
      "com.facebook.drift.annotations.ThriftIdlAnnotation",
      "com.facebook.presto.druid.zip.ZipFileEntry",
      "com.facebook.presto.druid.zip.ZipFileEntry$Flag",
      "com.facebook.presto.druid.zip.CentralDirectoryFileHeader",
      "com.facebook.presto.spi.ErrorCodeSupplier",
      "com.facebook.presto.druid.zip.ZipFileData",
      "com.facebook.presto.druid.zip.ZipFileEntry$Feature",
      "com.facebook.presto.druid.zip.ZipUtil",
      "com.facebook.drift.annotations.ThriftEnum"
    );
  } 
  private static void initMocksToAvoidTimeoutsInTheTests() throws ClassNotFoundException { 
    mock(Class.forName("com.facebook.presto.druid.DataInputSource", false, CentralDirectoryFileHeader_ESTest_scaffolding.class.getClassLoader()));
    mock(Class.forName("com.facebook.presto.druid.zip.ZipFileData", false, CentralDirectoryFileHeader_ESTest_scaffolding.class.getClassLoader()));
    mock(Class.forName("java.nio.charset.Charset", false, CentralDirectoryFileHeader_ESTest_scaffolding.class.getClassLoader()));
  }

  private static void resetClasses() {
    org.evosuite.runtime.classhandling.ClassResetter.getInstance().setClassLoader(CentralDirectoryFileHeader_ESTest_scaffolding.class.getClassLoader()); 

    org.evosuite.runtime.classhandling.ClassStateSupport.resetClasses(
      "com.facebook.presto.druid.zip.CentralDirectoryFileHeader",
      "com.facebook.presto.spi.ErrorType",
      "com.facebook.presto.spi.ErrorCode",
      "com.facebook.presto.druid.DruidErrorCode",
      "com.facebook.presto.druid.zip.ZipFileEntry$Feature",
      "com.facebook.presto.druid.zip.ZipFileEntry$Compression",
      "com.facebook.presto.druid.zip.ZipUtil",
      "com.facebook.presto.druid.zip.ZipFileData",
      "com.facebook.presto.spi.PrestoException",
      "com.facebook.presto.druid.zip.ExtraDataList",
      "com.facebook.presto.druid.zip.ZipFileEntry"
    );
  }
}
