/*
 * This file was automatically generated by EvoSuite
 * Sun Nov 21 02:13:24 GMT 2021
 */

package com.facebook.presto.cassandra;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import com.facebook.presto.cassandra.CassandraSplit;
import com.facebook.presto.spi.HostAddress;
import java.util.List;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class CassandraSplit_ESTest extends CassandraSplit_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      CassandraSplit cassandraSplit0 = null;
      try {
        cassandraSplit0 = new CassandraSplit(">Yn#^pj#fdkcSL9", ">Yn#^pj#fdkcSL9", ">Yn#^pj#fdkcSL9", ">Yn#^pj#fdkcSL9", ">Yn#^pj#fdkcSL9", (List<HostAddress>) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // addresses is null
         //
         verifyException("java.util.Objects", e);
      }
  }
}
