/*
 * This file was automatically generated by EvoSuite
 * Thu Nov 18 22:04:09 GMT 2021
 */

package com.facebook.presto.bytecode.expression;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import com.facebook.presto.bytecode.ParameterizedType;
import com.facebook.presto.bytecode.expression.BytecodeExpression;
import com.facebook.presto.bytecode.expression.ConstantBytecodeExpression;
import com.facebook.presto.bytecode.expression.GetFieldBytecodeExpression;
import com.facebook.presto.bytecode.expression.InlineIfBytecodeExpression;
import com.facebook.presto.bytecode.expression.InstanceOfBytecodeExpression;
import com.facebook.presto.bytecode.expression.NewArrayBytecodeExpression;
import com.facebook.presto.bytecode.instruction.Constant;
import java.lang.reflect.Array;
import java.util.List;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class NewArrayBytecodeExpression_ESTest extends NewArrayBytecodeExpression_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      ParameterizedType parameterizedType0 = ParameterizedType.typeFromJavaClassName("e.@V0K$9rvYgAe^%n/?");
      NewArrayBytecodeExpression newArrayBytecodeExpression0 = null;
      try {
        newArrayBytecodeExpression0 = new NewArrayBytecodeExpression(parameterizedType0, (BytecodeExpression) null);
        fail("Expecting exception: IllegalArgumentException");
      
      } catch(IllegalArgumentException e) {
         //
         // type Le/@V0K$9rvYgAe^%n/?; must be array type
         //
         verifyException("com.google.common.base.Preconditions", e);
      }
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      NewArrayBytecodeExpression newArrayBytecodeExpression0 = null;
      try {
        newArrayBytecodeExpression0 = new NewArrayBytecodeExpression((ParameterizedType) null, (-2742));
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // type is null
         //
         verifyException("java.util.Objects", e);
      }
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      Class<Integer> class0 = Integer.class;
      Class<InlineIfBytecodeExpression>[] classArray0 = (Class<InlineIfBytecodeExpression>[]) Array.newInstance(Class.class, 3);
      Class<InlineIfBytecodeExpression> class1 = InlineIfBytecodeExpression.class;
      classArray0[0] = class1;
      classArray0[1] = class1;
      classArray0[2] = class1;
      ParameterizedType parameterizedType0 = ParameterizedType.type(class0, classArray0);
      NewArrayBytecodeExpression newArrayBytecodeExpression0 = null;
      try {
        newArrayBytecodeExpression0 = new NewArrayBytecodeExpression(parameterizedType0, 2126);
        fail("Expecting exception: IllegalArgumentException");
      
      } catch(IllegalArgumentException e) {
         //
         // type Ljava/lang/Integer<Lcom/facebook/presto/bytecode/expression/InlineIfBytecodeExpression;Lcom/facebook/presto/bytecode/expression/InlineIfBytecodeExpression;Lcom/facebook/presto/bytecode/expression/InlineIfBytecodeExpression;>; must be array type
         //
         verifyException("com.google.common.base.Preconditions", e);
      }
  }

  @Test(timeout = 4000)
  public void test3()  throws Throwable  {
      Class<InstanceOfBytecodeExpression> class0 = InstanceOfBytecodeExpression.class;
      Class<InlineIfBytecodeExpression>[] classArray0 = (Class<InlineIfBytecodeExpression>[]) Array.newInstance(Class.class, 8);
      Class<InlineIfBytecodeExpression> class1 = InlineIfBytecodeExpression.class;
      classArray0[0] = class1;
      classArray0[1] = class1;
      classArray0[2] = classArray0[0];
      classArray0[3] = class1;
      classArray0[4] = classArray0[1];
      classArray0[5] = classArray0[0];
      classArray0[6] = classArray0[0];
      classArray0[7] = class1;
      ParameterizedType parameterizedType0 = ParameterizedType.type(class0, classArray0);
      NewArrayBytecodeExpression newArrayBytecodeExpression0 = null;
      try {
        newArrayBytecodeExpression0 = new NewArrayBytecodeExpression(parameterizedType0, (List<BytecodeExpression>) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("com.facebook.presto.bytecode.expression.NewArrayBytecodeExpression", e);
      }
  }

  @Test(timeout = 4000)
  public void test4()  throws Throwable  {
      Class<GetFieldBytecodeExpression> class0 = GetFieldBytecodeExpression.class;
      ConstantBytecodeExpression constantBytecodeExpression0 = new ConstantBytecodeExpression(class0, (Constant) null);
      NewArrayBytecodeExpression newArrayBytecodeExpression0 = null;
      try {
        newArrayBytecodeExpression0 = new NewArrayBytecodeExpression((ParameterizedType) null, constantBytecodeExpression0);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // type is null
         //
         verifyException("java.util.Objects", e);
      }
  }
}
