/*
 * This file was automatically generated by EvoSuite
 * Sat Nov 20 20:00:22 GMT 2021
 */

package com.facebook.presto.orc;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import com.facebook.presto.orc.OrcDataSourceId;
import com.facebook.presto.orc.OrcPermissionsException;
import java.util.MissingFormatArgumentException;
import java.util.UnknownFormatConversionException;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class OrcPermissionsException_ESTest extends OrcPermissionsException_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      OrcDataSourceId orcDataSourceId0 = new OrcDataSourceId("R^EJFs#f%^.MNY?GS0d");
      assertEquals("R^EJFs#f%^.MNY?GS0d", orcDataSourceId0.toString());
      assertNotNull(orcDataSourceId0);
      
      Object[] objectArray0 = new Object[6];
      OrcPermissionsException orcPermissionsException0 = null;
      try {
        orcPermissionsException0 = new OrcPermissionsException(orcDataSourceId0, "R^EJFs#f%^.MNY?GS0d", objectArray0);
        fail("Expecting exception: UnknownFormatConversionException");
      
      } catch(UnknownFormatConversionException e) {
         //
         // Conversion = '^'
         //
         verifyException("java.util.Formatter", e);
      }
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      OrcDataSourceId orcDataSourceId0 = new OrcDataSourceId("Ignored field \"%s\" (class %s) encountered; mapper configured not to allow this");
      assertEquals("Ignored field \"%s\" (class %s) encountered; mapper configured not to allow this", orcDataSourceId0.toString());
      assertNotNull(orcDataSourceId0);
      
      Object[] objectArray0 = new Object[0];
      OrcPermissionsException orcPermissionsException0 = null;
      try {
        orcPermissionsException0 = new OrcPermissionsException(orcDataSourceId0, "Ignored field \"%s\" (class %s) encountered; mapper configured not to allow this", objectArray0);
        fail("Expecting exception: MissingFormatArgumentException");
      
      } catch(MissingFormatArgumentException e) {
         //
         // Format specifier '%s'
         //
         verifyException("java.util.Formatter", e);
      }
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      OrcPermissionsException orcPermissionsException0 = null;
      try {
        orcPermissionsException0 = new OrcPermissionsException((OrcDataSourceId) null, (String) null, (Object[]) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
      }
  }

  @Test(timeout = 4000)
  public void test3()  throws Throwable  {
      Object[] objectArray0 = new Object[8];
      OrcPermissionsException orcPermissionsException0 = new OrcPermissionsException((OrcDataSourceId) null, "sL'bx UXi/k", objectArray0);
      assertEquals(8, objectArray0.length);
      assertEquals("org.evosuite.runtime.mock.java.lang.MockThrowable: sL'bx UXi/k [null]", orcPermissionsException0.getMessage());
      assertEquals("com.facebook.presto.orc.OrcPermissionsException: org.evosuite.runtime.mock.java.lang.MockThrowable: sL'bx UXi/k [null]", orcPermissionsException0.toString());
      assertNotNull(orcPermissionsException0);
  }
}
