/*
 * This file was automatically generated by EvoSuite
 * Sat Nov 20 19:58:12 GMT 2021
 */

package com.facebook.presto.orc;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import com.facebook.presto.orc.WriterEncryptionGroup;
import io.airlift.slice.Slice;
import java.util.List;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class WriterEncryptionGroup_ESTest extends WriterEncryptionGroup_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      WriterEncryptionGroup writerEncryptionGroup0 = null;
      try {
        writerEncryptionGroup0 = new WriterEncryptionGroup((List<Integer>) null, (Slice) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // nodes is null
         //
         verifyException("java.util.Objects", e);
      }
  }
}
