/*
 * This file was automatically generated by EvoSuite
 * Sun Nov 21 09:10:12 GMT 2021
 */

package com.facebook.presto.druid.authentication;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.shaded.org.mockito.Mockito.*;
import static org.evosuite.runtime.EvoAssertions.*;
import com.facebook.airlift.http.client.Request;
import com.facebook.presto.druid.DruidConfig;
import com.facebook.presto.druid.authentication.DruidBasicAuthHttpRequestFilter;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.evosuite.runtime.ViolatedAssumptionAnswer;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class DruidBasicAuthHttpRequestFilter_ESTest extends DruidBasicAuthHttpRequestFilter_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      DruidBasicAuthHttpRequestFilter druidBasicAuthHttpRequestFilter0 = null;
      try {
        druidBasicAuthHttpRequestFilter0 = new DruidBasicAuthHttpRequestFilter((DruidConfig) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("com.facebook.presto.druid.authentication.DruidBasicAuthHttpRequestFilter", e);
      }
  }
}
