/*
 * This file was automatically generated by EvoSuite
 * Mon Nov 22 09:27:43 GMT 2021
 */

package com.facebook.presto.tpcds.statistics;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import com.facebook.presto.tpcds.statistics.ColumnStatisticsData;
import com.facebook.presto.tpcds.statistics.TableStatisticsData;
import java.util.Map;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class TableStatisticsData_ESTest extends TableStatisticsData_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      TableStatisticsData tableStatisticsData0 = null;
      try {
        tableStatisticsData0 = new TableStatisticsData(1634L, (Map<String, ColumnStatisticsData>) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("com.google.common.collect.ImmutableMap", e);
      }
  }
}
