/**
 * Scaffolding file used to store all the setups needed to run 
 * tests automatically generated by EvoSuite
 * Sun Nov 21 01:19:07 GMT 2021
 */

package com.facebook.presto.accumulo;

import org.evosuite.runtime.annotation.EvoSuiteClassExclude;
import org.junit.BeforeClass;
import org.junit.Before;
import org.junit.After;
import org.evosuite.runtime.sandbox.Sandbox;
import org.evosuite.runtime.sandbox.Sandbox.SandboxMode;

@EvoSuiteClassExclude
public class AccumuloMetadata_ESTest_scaffolding {

  @org.junit.Rule 
  public org.evosuite.runtime.vnet.NonFunctionalRequirementRule nfr = new org.evosuite.runtime.vnet.NonFunctionalRequirementRule();

  private org.evosuite.runtime.thread.ThreadStopper threadStopper =  new org.evosuite.runtime.thread.ThreadStopper (org.evosuite.runtime.thread.KillSwitchHandler.getInstance(), 3000);


  @BeforeClass 
  public static void initEvoSuiteFramework() { 
    org.evosuite.runtime.RuntimeSettings.className = "com.facebook.presto.accumulo.AccumuloMetadata"; 
    org.evosuite.runtime.GuiSupport.initialize(); 
    org.evosuite.runtime.RuntimeSettings.maxNumberOfThreads = 100; 
    org.evosuite.runtime.RuntimeSettings.maxNumberOfIterationsPerLoop = 10000; 
    org.evosuite.runtime.RuntimeSettings.mockSystemIn = true; 
    org.evosuite.runtime.RuntimeSettings.sandboxMode = org.evosuite.runtime.sandbox.Sandbox.SandboxMode.RECOMMENDED; 
    org.evosuite.runtime.sandbox.Sandbox.initializeSecurityManagerForSUT(); 
    org.evosuite.runtime.classhandling.JDKClassResetter.init();
    setSystemProperties();
    initializeClasses();
    org.evosuite.runtime.Runtime.getInstance().resetRuntime(); 
  } 

  @Before 
  public void initTestCase(){ 
    threadStopper.storeCurrentThreads();
    threadStopper.startRecordingTime();
    org.evosuite.runtime.jvm.ShutdownHookHandler.getInstance().initHandler(); 
    org.evosuite.runtime.sandbox.Sandbox.goingToExecuteSUTCode(); 
    org.evosuite.runtime.GuiSupport.setHeadless(); 
    org.evosuite.runtime.Runtime.getInstance().resetRuntime(); 
    org.evosuite.runtime.agent.InstrumentingAgent.activate(); 
  } 

  @After 
  public void doneWithTestCase(){ 
    threadStopper.killAndJoinClientThreads();
    org.evosuite.runtime.jvm.ShutdownHookHandler.getInstance().safeExecuteAddedHooks(); 
    org.evosuite.runtime.classhandling.JDKClassResetter.reset(); 
    resetClasses(); 
    org.evosuite.runtime.sandbox.Sandbox.doneWithExecutingSUTCode(); 
    org.evosuite.runtime.agent.InstrumentingAgent.deactivate(); 
    org.evosuite.runtime.GuiSupport.restoreHeadlessMode(); 
  } 

  public static void setSystemProperties() {
 
    /*No java.lang.System property to set*/
  }

  private static void initializeClasses() {
    org.evosuite.runtime.classhandling.ClassStateSupport.initializeClasses(AccumuloMetadata_ESTest_scaffolding.class.getClassLoader() ,
      "com.facebook.presto.spi.ConnectorInsertTableHandle",
      "com.facebook.presto.spi.connector.ConnectorMetadata",
      "com.facebook.presto.spi.TableNotFoundException",
      "com.facebook.presto.accumulo.AccumuloMetadata",
      "com.facebook.presto.spi.NotFoundException",
      "com.facebook.presto.spi.ConnectorTableLayoutHandle",
      "com.facebook.presto.spi.ErrorCodeSupplier",
      "com.facebook.presto.spi.ConnectorTableHandle",
      "com.facebook.presto.spi.PrestoException",
      "com.facebook.presto.spi.ConnectorOutputTableHandle"
    );
  } 

  private static void resetClasses() {
    org.evosuite.runtime.classhandling.ClassResetter.getInstance().setClassLoader(AccumuloMetadata_ESTest_scaffolding.class.getClassLoader()); 

    org.evosuite.runtime.classhandling.ClassStateSupport.resetClasses(
      "com.facebook.presto.accumulo.AccumuloMetadata",
      "com.facebook.presto.spi.ErrorType",
      "com.facebook.presto.spi.ErrorCode",
      "com.facebook.presto.accumulo.AccumuloErrorCode",
      "com.facebook.presto.spi.StandardErrorCode",
      "com.google.common.collect.ImmutableCollection",
      "com.google.common.collect.ImmutableList",
      "com.google.common.collect.RegularImmutableList",
      "com.facebook.presto.accumulo.AccumuloConnectorId",
      "org.apache.accumulo.core.client.Connector",
      "org.apache.accumulo.core.client.impl.ConnectorImpl",
      "com.facebook.presto.accumulo.conf.AccumuloConfig",
      "io.airlift.units.Duration",
      "io.airlift.units.Preconditions",
      "com.facebook.presto.spi.transaction.IsolationLevel",
      "com.facebook.presto.transaction.TransactionManager",
      "com.facebook.presto.transaction.NoOpTransactionManager",
      "com.facebook.presto.common.block.BlockEncodingManager",
      "com.facebook.presto.common.block.VariableWidthBlockEncoding",
      "com.facebook.presto.common.block.ByteArrayBlockEncoding",
      "com.facebook.presto.common.block.ShortArrayBlockEncoding",
      "com.facebook.presto.common.block.IntArrayBlockEncoding",
      "com.facebook.presto.common.block.LongArrayBlockEncoding",
      "com.facebook.presto.common.block.Int128ArrayBlockEncoding",
      "com.facebook.presto.common.block.DictionaryBlockEncoding",
      "com.facebook.presto.common.block.ArrayBlockEncoding",
      "com.facebook.presto.common.block.MapBlockEncoding",
      "com.facebook.presto.common.block.SingleMapBlockEncoding",
      "com.facebook.presto.common.block.RowBlockEncoding",
      "com.facebook.presto.common.block.SingleRowBlockEncoding",
      "com.facebook.presto.common.block.RunLengthBlockEncoding",
      "com.facebook.presto.common.block.LazyBlockEncoding",
      "com.facebook.presto.sql.analyzer.FeaturesConfig",
      "com.facebook.presto.sql.analyzer.FeaturesConfig$JoinDistributionType",
      "io.airlift.units.DataSize",
      "com.facebook.presto.sql.analyzer.FeaturesConfig$JoinReorderingStrategy",
      "com.facebook.presto.sql.analyzer.FeaturesConfig$PartialMergePushdownStrategy",
      "com.facebook.presto.sql.analyzer.RegexLibrary",
      "com.facebook.presto.operator.aggregation.histogram.HistogramGroupImplementation",
      "com.facebook.presto.operator.aggregation.arrayagg.ArrayAggGroupImplementation",
      "com.facebook.presto.operator.aggregation.multimapagg.MultimapAggGroupImplementation",
      "com.facebook.presto.sql.analyzer.FeaturesConfig$PartialAggregationStrategy",
      "com.facebook.presto.sql.analyzer.FeaturesConfig$AggregationPartitioningMergingStrategy",
      "com.facebook.presto.sql.analyzer.FeaturesConfig$PartitioningPrecisionStrategy",
      "com.facebook.presto.sql.analyzer.FeaturesConfig$AggregationIfToFilterRewriteStrategy",
      "com.facebook.presto.metadata.HandleResolver",
      "com.google.common.util.concurrent.GwtFuturesCatchingSpecialization",
      "com.google.common.util.concurrent.Futures",
      "com.google.common.util.concurrent.GwtFluentFutureCatchingSpecialization",
      "com.google.common.util.concurrent.FluentFuture",
      "com.google.common.util.concurrent.ImmediateFuture",
      "com.google.common.util.concurrent.ImmediateFuture$ImmediateSuccessfulFuture",
      "com.facebook.presto.operator.Operator",
      "com.facebook.presto.spi.ConnectorId",
      "com.facebook.presto.operator.ExchangeOperator",
      "com.facebook.presto.metadata.HandleResolver$MaterializedHandleResolver",
      "com.facebook.presto.metadata.RemoteHandleResolver",
      "com.facebook.presto.connector.system.SystemHandleResolver",
      "com.facebook.presto.connector.informationSchema.InformationSchemaHandleResolver",
      "com.facebook.presto.split.EmptySplitHandleResolver",
      "com.facebook.presto.metadata.HandleResolver$MaterializedFunctionHandleResolver",
      "com.facebook.presto.metadata.BuiltInFunctionNamespaceHandleResolver",
      "com.facebook.presto.metadata.SessionFunctionHandleResolver",
      "com.facebook.presto.metadata.FunctionAndTypeManager",
      "com.facebook.presto.metadata.BuiltInTypeAndFunctionNamespaceManager$FunctionMap",
      "com.google.common.collect.AbstractMultimap",
      "com.google.common.collect.BaseImmutableMultimap",
      "com.google.common.collect.ImmutableMultimap",
      "com.google.common.collect.ImmutableListMultimap",
      "com.google.common.collect.EmptyImmutableListMultimap",
      "com.facebook.presto.metadata.BuiltInFunction",
      "com.facebook.presto.metadata.SqlScalarFunction",
      "com.facebook.presto.metadata.BuiltInTypeAndFunctionNamespaceManager$MagicLiteralFunction",
      "com.facebook.presto.spi.function.Signature",
      "com.facebook.presto.spi.function.FunctionKind",
      "com.facebook.presto.common.type.TypeSignature",
      "com.facebook.presto.common.type.TypeSignatureBase",
      "com.google.common.cache.CacheBuilder$1",
      "com.google.common.base.Suppliers",
      "com.google.common.base.Suppliers$SupplierOfInstance",
      "com.google.common.cache.CacheStats",
      "com.google.common.cache.CacheBuilder$2",
      "com.google.common.base.Ticker$1",
      "com.google.common.base.Ticker",
      "com.google.common.cache.CacheBuilder$3",
      "com.google.common.cache.CacheBuilder",
      "com.google.common.cache.CacheLoader",
      "com.google.common.cache.CacheLoader$FunctionToCacheLoader",
      "com.google.common.cache.LocalCache$LocalManualCache",
      "com.google.common.cache.LocalCache$LocalLoadingCache",
      "com.google.common.cache.LocalCache$1",
      "com.google.common.cache.LocalCache$2",
      "com.google.common.cache.LocalCache",
      "com.google.common.cache.LocalCache$Strength",
      "com.google.common.base.MoreObjects",
      "com.google.common.base.Equivalence",
      "com.google.common.base.Equivalence$Equals",
      "com.google.common.cache.CacheBuilder$OneWeigher",
      "com.google.common.cache.CacheBuilder$NullListener",
      "com.google.common.cache.LocalCache$EntryFactory",
      "com.google.common.cache.LocalCache$Segment",
      "com.google.common.cache.LocalCache$AccessQueue",
      "com.google.common.cache.LocalCache$AbstractReferenceEntry",
      "com.google.common.cache.LocalCache$AccessQueue$1",
      "com.google.common.cache.LocalCache$WriteQueue",
      "com.google.common.cache.LocalCache$WriteQueue$1",
      "com.facebook.presto.metadata.FunctionListBuilder",
      "com.facebook.presto.operator.window.WindowAnnotationsParser",
      "com.google.common.collect.ImmutableList$Builder",
      "com.facebook.presto.operator.window.SqlWindowFunction",
      "com.facebook.presto.operator.window.AbstractWindowFunctionSupplier",
      "com.facebook.presto.operator.window.ReflectionWindowFunctionSupplier",
      "com.google.common.collect.SingletonImmutableList",
      "com.facebook.presto.spi.function.TypeVariableConstraint",
      "com.facebook.presto.metadata.SqlAggregationFunction",
      "com.facebook.presto.operator.aggregation.AggregationFromAnnotationsParser",
      "com.facebook.presto.operator.ParametricImplementationsGroup",
      "com.facebook.presto.operator.ParametricImplementationsGroup$Builder",
      "com.facebook.presto.spi.function.SqlFunctionVisibility",
      "com.facebook.presto.operator.aggregation.AggregationHeader",
      "com.facebook.presto.operator.annotations.FunctionsParserHelper",
      "com.google.common.collect.SingletonImmutableSet",
      "com.google.common.collect.Iterators",
      "com.google.common.collect.UnmodifiableIterator",
      "com.google.common.collect.UnmodifiableListIterator",
      "com.google.common.collect.AbstractIndexedListIterator",
      "com.google.common.collect.Iterators$ArrayItr",
      "com.google.common.collect.Iterators$9",
      "com.facebook.presto.operator.aggregation.AggregationImplementation$Parser",
      "com.facebook.presto.spi.function.InvocationConvention$InvocationReturnConvention",
      "com.google.common.collect.Iterables",
      "com.facebook.presto.operator.aggregation.AggregationMetadata$ParameterMetadata$ParameterType",
      "com.facebook.presto.operator.aggregation.AggregationImplementation$AggregateNativeContainerType",
      "com.facebook.presto.util.Reflection",
      "com.facebook.presto.operator.aggregation.AggregationImplementation",
      "com.facebook.presto.operator.annotations.ImplementationDependency$Factory",
      "com.facebook.presto.operator.annotations.ScalarImplementationDependency",
      "com.facebook.presto.operator.annotations.OperatorImplementationDependency",
      "com.facebook.presto.operator.aggregation.ParametricAggregation",
      "com.google.common.collect.ImmutableBiMapFauxverideShim",
      "com.google.common.collect.ImmutableBiMap",
      "com.google.common.collect.SingletonImmutableBiMap",
      "com.facebook.presto.common.type.TypeSignatureParameter",
      "com.facebook.presto.common.type.ParameterKind",
      "com.facebook.presto.common.type.TypeSignatureParameter$1",
      "com.facebook.presto.operator.aggregation.RealAverageAggregation",
      "com.facebook.presto.common.type.AbstractType",
      "com.facebook.presto.common.type.AbstractVariableWidthType",
      "com.facebook.presto.common.type.AbstractVarcharType",
      "com.facebook.presto.common.type.VarcharType",
      "com.facebook.presto.operator.aggregation.StatisticalDigestAggregationFunction",
      "com.facebook.presto.operator.aggregation.state.StatisticalDigestStateFactory",
      "com.google.common.collect.ObjectArrays",
      "com.facebook.presto.operator.aggregation.QuantileDigestAggregationFunction",
      "com.facebook.presto.operator.aggregation.MergeStatisticalDigestFunction",
      "com.facebook.presto.operator.aggregation.MergeQuantileDigestFunction",
      "com.facebook.presto.operator.scalar.annotations.ScalarFromAnnotationsParser",
      "com.facebook.presto.operator.scalar.annotations.ScalarImplementationHeader",
      "com.facebook.presto.operator.scalar.ScalarHeader",
      "com.facebook.presto.util.Failures",
      "com.facebook.presto.operator.scalar.annotations.ScalarFromAnnotationsParser$ScalarHeaderAndMethods",
      "com.facebook.presto.operator.scalar.annotations.ParametricScalarImplementation$Parser",
      "com.google.common.primitives.Primitives",
      "com.facebook.presto.operator.annotations.TypeImplementationDependency",
      "com.facebook.presto.operator.scalar.BuiltInScalarFunctionImplementation$NullConvention",
      "com.facebook.presto.operator.scalar.BuiltInScalarFunctionImplementation$ArgumentProperty",
      "com.facebook.presto.operator.scalar.BuiltInScalarFunctionImplementation$ArgumentType",
      "com.facebook.presto.operator.scalar.BuiltInScalarFunctionImplementation$1",
      "com.facebook.presto.operator.scalar.annotations.ParametricScalarImplementation$ParametricScalarImplementationChoice",
      "com.facebook.presto.operator.scalar.BuiltInScalarFunctionImplementation$ReturnPlaceConvention",
      "com.facebook.presto.operator.scalar.annotations.ParametricScalarImplementation",
      "com.facebook.presto.operator.scalar.annotations.ParametricScalarImplementation$SpecializedSignature",
      "com.google.common.collect.Maps",
      "com.google.common.collect.Sets",
      "com.facebook.presto.operator.scalar.annotations.ParametricScalarImplementation$Builder",
      "com.google.common.collect.ImmutableMapEntrySet",
      "com.google.common.collect.ImmutableMapEntrySet$RegularEntrySet",
      "com.google.common.collect.RegularImmutableMap$Values",
      "com.google.common.collect.ImmutableList$1",
      "com.facebook.presto.operator.scalar.ParametricScalar",
      "com.google.common.base.CharMatcher",
      "com.google.common.base.CharMatcher$FastMatcher",
      "com.google.common.base.CharMatcher$Is",
      "com.google.common.base.CharMatcher$InRange",
      "com.google.common.base.CaseFormat",
      "com.google.common.base.Ascii",
      "com.facebook.presto.operator.annotations.LiteralImplementationDependency",
      "com.facebook.presto.operator.scalar.annotations.OperatorValidator",
      "com.facebook.presto.operator.scalar.annotations.OperatorValidator$1",
      "com.google.common.base.Joiner",
      "com.facebook.presto.spi.function.LongVariableConstraint",
      "com.google.common.base.Strings",
      "com.facebook.presto.common.type.AbstractIntType",
      "com.facebook.presto.common.type.DateType",
      "org.apache.log4j.Category",
      "org.apache.log4j.Logger",
      "org.apache.log4j.Hierarchy",
      "org.apache.log4j.spi.RootLogger",
      "org.apache.log4j.Priority",
      "org.apache.log4j.Level",
      "org.apache.log4j.or.DefaultRenderer",
      "org.apache.log4j.or.RendererMap",
      "org.apache.log4j.DefaultCategoryFactory",
      "org.apache.log4j.spi.DefaultRepositorySelector",
      "org.apache.log4j.helpers.OptionConverter",
      "org.apache.log4j.helpers.Loader",
      "org.apache.log4j.helpers.LogLog",
      "org.apache.log4j.PropertyConfigurator",
      "org.apache.log4j.LogManager",
      "org.apache.log4j.CategoryKey",
      "org.apache.log4j.ProvisionNode",
      "org.apache.accumulo.core.client.ZooKeeperInstance",
      "org.apache.commons.configuration.event.EventSource",
      "org.apache.commons.configuration.AbstractConfiguration",
      "org.apache.commons.configuration.CompositeConfiguration",
      "org.apache.accumulo.core.client.ClientConfiguration",
      "org.apache.commons.configuration.BaseConfiguration",
      "org.apache.commons.logging.impl.NoOpLog",
      "org.apache.commons.collections.map.AbstractHashedMap",
      "org.apache.commons.collections.map.AbstractLinkedMap",
      "org.apache.commons.collections.map.LinkedMap",
      "org.apache.commons.collections.map.AbstractHashedMap$HashEntry",
      "org.apache.commons.collections.map.AbstractLinkedMap$LinkEntry",
      "org.apache.commons.configuration.PropertyConverter",
      "org.apache.commons.collections.iterators.SingletonIterator",
      "org.apache.accumulo.fate.zookeeper.ZooCacheFactory",
      "org.apache.commons.lang.text.StrMatcher$CharMatcher",
      "org.apache.commons.lang.text.StrMatcher$CharSetMatcher",
      "org.apache.commons.lang.text.StrMatcher$TrimMatcher",
      "org.apache.commons.lang.text.StrMatcher$NoMatcher",
      "org.apache.commons.lang.text.StrMatcher",
      "org.apache.commons.lang.text.StrMatcher$StringMatcher",
      "org.apache.commons.lang.text.StrSubstitutor",
      "org.apache.commons.lang.text.StrLookup$MapStrLookup",
      "org.apache.commons.lang.text.StrLookup",
      "org.apache.commons.configuration.interpol.ConstantLookup",
      "org.apache.commons.configuration.interpol.ConfigurationInterpolator",
      "org.apache.commons.configuration.AbstractConfiguration$1",
      "org.apache.commons.lang.text.StrBuilder",
      "org.apache.accumulo.core.conf.AccumuloConfiguration",
      "org.apache.accumulo.fate.zookeeper.ZooCache",
      "org.apache.accumulo.fate.zookeeper.ZooReader",
      "org.apache.accumulo.fate.util.Retry",
      "org.apache.accumulo.fate.util.Retry$RetryFactoryBuilder",
      "org.apache.zookeeper.data.Id",
      "org.apache.zookeeper.data.ACL",
      "org.apache.zookeeper.ZooDefs$Ids",
      "org.apache.accumulo.fate.zookeeper.ZooUtil",
      "org.apache.accumulo.fate.zookeeper.ZooUtil$ZooKeeperConnectionInfo",
      "org.apache.accumulo.fate.zookeeper.ZooCache$ZCacheWatcher",
      "org.apache.accumulo.fate.zookeeper.ZooCache$ZooRunnable",
      "org.apache.accumulo.fate.zookeeper.ZooCache$2",
      "org.apache.accumulo.fate.zookeeper.ZooSession",
      "org.apache.accumulo.fate.zookeeper.ZooSession$ZooWatcher",
      "org.apache.accumulo.fate.zookeeper.ZooSession$ZooSessionInfo",
      "org.apache.zookeeper.Environment",
      "org.apache.zookeeper.Version",
      "org.apache.zookeeper.version.Info",
      "org.apache.zookeeper.Environment$Entry",
      "org.apache.zookeeper.ZooKeeper",
      "org.apache.zookeeper.ZooKeeper$ZKWatchManager",
      "org.apache.zookeeper.client.ConnectStringParser",
      "org.apache.zookeeper.client.StaticHostProvider",
      "org.apache.zookeeper.client.StaticHostProvider$1",
      "org.apache.zookeeper.ClientCnxn",
      "org.apache.zookeeper.ClientCnxnSocket",
      "org.apache.zookeeper.ClientCnxnSocketNIO",
      "org.apache.zookeeper.ZooKeeper$States",
      "org.apache.zookeeper.server.ZooKeeperThread",
      "org.apache.zookeeper.ClientCnxn$SendThread",
      "org.apache.zookeeper.server.ZooKeeperThread$1",
      "org.apache.zookeeper.ClientCnxn$EventThread",
      "org.apache.zookeeper.Watcher$Event$KeeperState",
      "org.apache.accumulo.fate.util.UtilWaitThread",
      "com.facebook.presto.accumulo.metadata.ZooKeeperMetadataManager",
      "org.apache.accumulo.core.client.impl.Credentials",
      "org.apache.accumulo.core.util.Base64",
      "org.apache.commons.codec.binary.BaseNCodec",
      "org.apache.commons.codec.binary.Base64",
      "org.apache.commons.codec.binary.StringUtils",
      "org.apache.commons.codec.Charsets",
      "org.apache.commons.codec.binary.BaseNCodec$Context"
    );
  }
}
