/*
 * This file was automatically generated by EvoSuite
 * Mon Nov 22 19:10:21 GMT 2021
 */

package com.facebook.presto.connector.thrift;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.shaded.org.mockito.Mockito.*;
import static org.evosuite.runtime.EvoAssertions.*;
import com.facebook.presto.connector.thrift.ThriftConnectorSplit;
import com.facebook.presto.spi.HostAddress;
import com.facebook.presto.thrift.api.connector.PrestoThriftId;
import java.util.List;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.evosuite.runtime.ViolatedAssumptionAnswer;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class ThriftConnectorSplit_ESTest extends ThriftConnectorSplit_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      PrestoThriftId prestoThriftId0 = mock(PrestoThriftId.class, new ViolatedAssumptionAnswer());
      ThriftConnectorSplit thriftConnectorSplit0 = null;
      try {
        thriftConnectorSplit0 = new ThriftConnectorSplit(prestoThriftId0, (List<HostAddress>) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // addresses is null
         //
         verifyException("java.util.Objects", e);
      }
  }
}
