/**
 * Scaffolding file used to store all the setups needed to run 
 * tests automatically generated by EvoSuite
 * Sun Nov 21 13:52:56 GMT 2021
 */

package com.facebook.presto.raptor.storage.organization;

import org.evosuite.runtime.annotation.EvoSuiteClassExclude;
import org.junit.BeforeClass;
import org.junit.Before;
import org.junit.After;
import org.junit.AfterClass;
import org.evosuite.runtime.sandbox.Sandbox;
import org.evosuite.runtime.sandbox.Sandbox.SandboxMode;

@EvoSuiteClassExclude
public class ShardOrganizerUtil_ESTest_scaffolding {

  @org.junit.Rule 
  public org.evosuite.runtime.vnet.NonFunctionalRequirementRule nfr = new org.evosuite.runtime.vnet.NonFunctionalRequirementRule();

  private static final java.util.Properties defaultProperties = (java.util.Properties) java.lang.System.getProperties().clone(); 

  private org.evosuite.runtime.thread.ThreadStopper threadStopper =  new org.evosuite.runtime.thread.ThreadStopper (org.evosuite.runtime.thread.KillSwitchHandler.getInstance(), 3000);


  @BeforeClass 
  public static void initEvoSuiteFramework() { 
    org.evosuite.runtime.RuntimeSettings.className = "com.facebook.presto.raptor.storage.organization.ShardOrganizerUtil"; 
    org.evosuite.runtime.GuiSupport.initialize(); 
    org.evosuite.runtime.RuntimeSettings.maxNumberOfThreads = 100; 
    org.evosuite.runtime.RuntimeSettings.maxNumberOfIterationsPerLoop = 10000; 
    org.evosuite.runtime.RuntimeSettings.mockSystemIn = true; 
    org.evosuite.runtime.RuntimeSettings.sandboxMode = org.evosuite.runtime.sandbox.Sandbox.SandboxMode.RECOMMENDED; 
    org.evosuite.runtime.sandbox.Sandbox.initializeSecurityManagerForSUT(); 
    org.evosuite.runtime.classhandling.JDKClassResetter.init();
    setSystemProperties();
    initializeClasses();
    org.evosuite.runtime.Runtime.getInstance().resetRuntime(); 
  } 

  @AfterClass 
  public static void clearEvoSuiteFramework(){ 
    Sandbox.resetDefaultSecurityManager(); 
    java.lang.System.setProperties((java.util.Properties) defaultProperties.clone()); 
  } 

  @Before 
  public void initTestCase(){ 
    threadStopper.storeCurrentThreads();
    threadStopper.startRecordingTime();
    org.evosuite.runtime.jvm.ShutdownHookHandler.getInstance().initHandler(); 
    org.evosuite.runtime.sandbox.Sandbox.goingToExecuteSUTCode(); 
    setSystemProperties(); 
    org.evosuite.runtime.GuiSupport.setHeadless(); 
    org.evosuite.runtime.Runtime.getInstance().resetRuntime(); 
    org.evosuite.runtime.agent.InstrumentingAgent.activate(); 
  } 

  @After 
  public void doneWithTestCase(){ 
    threadStopper.killAndJoinClientThreads();
    org.evosuite.runtime.jvm.ShutdownHookHandler.getInstance().safeExecuteAddedHooks(); 
    org.evosuite.runtime.classhandling.JDKClassResetter.reset(); 
    resetClasses(); 
    org.evosuite.runtime.sandbox.Sandbox.doneWithExecutingSUTCode(); 
    org.evosuite.runtime.agent.InstrumentingAgent.deactivate(); 
    org.evosuite.runtime.GuiSupport.restoreHeadlessMode(); 
  } 

  public static void setSystemProperties() {
 
    java.lang.System.setProperties((java.util.Properties) defaultProperties.clone()); 
    java.lang.System.setProperty("file.encoding", "UTF-8"); 
    java.lang.System.setProperty("java.awt.headless", "true"); 
    java.lang.System.setProperty("java.io.tmpdir", "/tmp"); 
    java.lang.System.setProperty("user.dir", "/mnt/c/Users/Helen/Documents/DataScience18668/GroupProject/project/presto/presto-raptor"); 
    java.lang.System.setProperty("user.home", "/home/helen"); 
    java.lang.System.setProperty("user.language", "en"); 
    java.lang.System.setProperty("user.name", "helen"); 
    java.lang.System.setProperty("user.timezone", "America/Los_Angeles"); 
    java.lang.System.setProperty("sun.management.compiler", "HotSpot 64-Bit Tiered Compilers"); 
  }

  private static void initializeClasses() {
    org.evosuite.runtime.classhandling.ClassStateSupport.initializeClasses(ShardOrganizerUtil_ESTest_scaffolding.class.getClassLoader() ,
      "com.facebook.presto.common.type.AbstractType",
      "com.google.common.collect.ImmutableList$SubList",
      "com.google.common.collect.ListMultimap",
      "org.openjdk.jol.util.VMSupport$MyLongs4",
      "io.airlift.slice.SliceInput",
      "com.facebook.presto.common.type.TypeSignature",
      "org.openjdk.jol.util.VMSupport$MyInts4",
      "com.google.common.collect.RegularImmutableList",
      "org.openjdk.jol.info.FieldData",
      "io.airlift.slice.Slices",
      "com.facebook.presto.common.QualifiedObjectName",
      "org.skife.jdbi.v2.TransactionConsumer",
      "org.openjdk.jol.util.VMSupport$MyBytes4",
      "com.google.common.collect.ImmutableMap$IteratorBasedImmutableMap$1EntrySetImpl",
      "com.facebook.presto.raptor.storage.organization.ShardOrganizerUtil$1",
      "com.google.common.collect.ImmutableMapKeySet",
      "com.facebook.presto.common.block.BlockBuilder",
      "org.openjdk.jol.util.VMSupport$MyChars4",
      "com.google.common.collect.BaseImmutableMultimap",
      "com.facebook.presto.common.block.UncheckedBlock",
      "com.google.common.base.Converter$IdentityConverter",
      "com.facebook.presto.common.function.SqlFunctionProperties",
      "org.skife.jdbi.v2.tweak.HandleConsumer",
      "com.google.common.collect.Range",
      "com.google.common.collect.SortedMapDifference",
      "com.google.common.collect.ImmutableMap$IteratorBasedImmutableMap",
      "org.openjdk.jol.info.ClassLayout",
      "com.google.common.base.Predicate",
      "com.google.common.collect.ImmutableListMultimap",
      "io.airlift.slice.SliceTooLargeException",
      "com.google.common.collect.Maps$AbstractFilteredMap",
      "com.facebook.presto.common.type.AbstractLongType",
      "com.facebook.presto.common.GenericInternalException",
      "org.openjdk.jol.util.VMSupport$SizeInfo",
      "org.skife.jdbi.v2.TransactionIsolationLevel",
      "io.airlift.slice.Slice",
      "com.facebook.presto.common.type.TypeSignatureParameter",
      "com.google.common.collect.ImmutableAsList",
      "io.airlift.slice.SliceOutput",
      "com.google.common.base.MoreObjects$ToStringHelper",
      "com.facebook.presto.raptor.storage.organization.OrganizationSet",
      "com.google.common.collect.Maps$FilteredEntryMap",
      "com.google.common.collect.RegularImmutableAsList",
      "com.google.common.collect.ImmutableMapEntrySet",
      "com.google.common.collect.UnmodifiableListIterator",
      "com.google.common.collect.ImmutableMultimap",
      "com.google.common.collect.Maps$Accumulator",
      "com.facebook.presto.raptor.metadata.Distribution",
      "com.google.common.collect.RangeGwtSerializationDependencies",
      "com.google.common.collect.Maps$BiMapConverter",
      "org.skife.jdbi.v2.tweak.HandleCallback",
      "com.google.common.collect.ImmutableList$1",
      "com.facebook.presto.raptor.metadata.MetadataDao",
      "io.airlift.slice.BasicSliceInput",
      "com.facebook.presto.raptor.storage.organization.ShardRange",
      "com.google.common.collect.MapDifference",
      "org.openjdk.jol.layouters.CurrentLayouter",
      "com.google.common.collect.ImmutableMap$MapViewOfValuesAsSingletonSets",
      "com.facebook.presto.common.type.FixedWidthType",
      "org.openjdk.jol.util.VMSupport$CompressedOopsClass",
      "com.google.common.collect.UnmodifiableIterator",
      "org.openjdk.jol.info.FieldLayout",
      "com.facebook.presto.raptor.storage.organization.TemporalFunction",
      "com.google.common.collect.ImmutableMapValues",
      "com.google.common.collect.Maps$FilteredEntryNavigableMap",
      "com.facebook.presto.common.type.DoubleType",
      "org.skife.jdbi.v2.IDBI",
      "org.openjdk.jol.util.VMSupport$VMOptions",
      "com.google.common.base.Converter$ConverterComposition",
      "org.openjdk.jol.datamodel.DataModel",
      "org.skife.jdbi.v2.exceptions.DBIException",
      "com.google.common.collect.AbstractNavigableMap",
      "com.google.common.collect.ImmutableEnumMap",
      "com.google.common.collect.ImmutableCollection",
      "org.openjdk.jol.util.VMSupport",
      "org.openjdk.jol.info.ClassData",
      "com.facebook.presto.common.type.TypeSignatureBase",
      "com.google.common.collect.ImmutableList$ReverseImmutableList",
      "com.facebook.presto.common.type.UserDefinedType",
      "com.facebook.presto.raptor.metadata.TableColumn",
      "com.google.common.collect.SingletonImmutableList",
      "com.google.common.base.Converter",
      "com.google.common.collect.ImmutableSetMultimap",
      "com.google.common.collect.ImmutableCollection$Builder",
      "com.google.common.collect.Maps$8",
      "com.google.common.collect.BiMap",
      "com.google.common.collect.IndexedImmutableSet",
      "org.openjdk.jol.util.VMSupport$HeaderClass",
      "com.google.common.base.Function",
      "com.google.common.collect.ImmutableSet",
      "com.google.common.collect.ImmutableMap",
      "com.facebook.presto.common.type.BigintType",
      "com.google.common.collect.AbstractIndexedListIterator",
      "com.facebook.presto.raptor.storage.organization.ShardOrganizerUtil",
      "org.openjdk.jol.util.VMSupport$MyDoubles4",
      "io.airlift.slice.BasicSliceOutput",
      "com.facebook.presto.common.type.TypeSignature$EnumMapParsingData",
      "com.facebook.presto.raptor.metadata.ShardMetadata",
      "io.airlift.slice.FixedLengthSliceInput",
      "com.google.common.base.Converter$ReverseConverter",
      "com.facebook.presto.common.type.AbstractIntType",
      "com.google.common.collect.Maps$ViewCachingAbstractMap",
      "com.google.common.collect.Maps$IteratorBasedAbstractMap",
      "org.openjdk.jol.util.VMSupport$2",
      "org.openjdk.jol.util.MathUtil",
      "org.openjdk.jol.util.VMSupport$1",
      "com.facebook.presto.raptor.storage.organization.ShardIndexInfo",
      "com.google.common.collect.Maps$FilteredEntryBiMap",
      "com.google.common.collect.ImmutableMap$1",
      "com.facebook.presto.common.type.TimestampType",
      "com.google.common.collect.ImmutableList$Builder",
      "com.google.common.collect.ImmutableMultimap$Builder",
      "org.openjdk.jol.util.VMSupport$MyBooleans4",
      "com.google.common.collect.AbstractMultimap",
      "com.facebook.presto.common.type.BooleanType",
      "com.google.common.collect.Multimap",
      "org.openjdk.jol.datamodel.CurrentDataModel",
      "com.google.common.collect.ImmutableBiMap",
      "org.openjdk.jol.util.VMSupport$MyShorts4",
      "com.facebook.presto.common.type.IntegerType",
      "org.openjdk.jol.util.VMSupport$MyObject5",
      "com.google.common.collect.ImmutableList",
      "org.openjdk.jol.util.VMSupport$MyObject3",
      "org.openjdk.jol.util.VMSupport$MyObject4",
      "org.openjdk.jol.util.VMSupport$MyObject1",
      "org.openjdk.jol.util.VMSupport$MyObject2",
      "com.google.common.collect.ImmutableBiMapFauxverideShim",
      "com.google.common.collect.Maps$FilteredEntrySortedMap",
      "com.facebook.presto.common.block.BlockBuilderStatus",
      "com.facebook.presto.common.type.Type",
      "com.facebook.presto.raptor.metadata.Table",
      "com.google.common.base.Equivalence",
      "org.openjdk.jol.layouters.Layouter",
      "org.openjdk.jol.util.VMSupport$MyFloats4",
      "com.google.common.collect.Maps",
      "com.google.common.collect.ImmutableMap$Builder",
      "com.google.common.base.Converter$FunctionBasedConverter",
      "com.google.common.collect.SetMultimap",
      "com.google.common.collect.Maps$EntryTransformer",
      "org.skife.jdbi.v2.Handle",
      "org.skife.jdbi.v2.exceptions.CallbackFailedException",
      "org.skife.jdbi.v2.TransactionCallback",
      "com.facebook.presto.common.block.Block",
      "com.facebook.presto.common.type.DateType"
    );
  } 

  private static void resetClasses() {
    org.evosuite.runtime.classhandling.ClassResetter.getInstance().setClassLoader(ShardOrganizerUtil_ESTest_scaffolding.class.getClassLoader()); 

    org.evosuite.runtime.classhandling.ClassStateSupport.resetClasses(
      "com.facebook.presto.raptor.storage.organization.ShardOrganizerUtil",
      "com.facebook.presto.common.type.AbstractType",
      "com.facebook.presto.common.type.TypeSignature",
      "com.facebook.presto.common.type.TypeSignatureBase",
      "com.facebook.presto.common.type.BooleanType",
      "com.facebook.presto.common.type.AbstractLongType",
      "com.facebook.presto.common.type.BigintType",
      "com.facebook.presto.common.type.TimestampType",
      "com.facebook.presto.common.type.AbstractIntType",
      "com.facebook.presto.common.type.IntegerType",
      "com.facebook.presto.common.type.DoubleType",
      "com.facebook.presto.common.type.DateType",
      "com.facebook.presto.raptor.storage.organization.ShardOrganizerUtil$1",
      "org.openjdk.jol.info.ClassLayout",
      "org.openjdk.jol.layouters.CurrentLayouter",
      "org.openjdk.jol.info.ClassData",
      "org.openjdk.jol.info.FieldData",
      "org.openjdk.jol.util.VMSupport$1",
      "org.openjdk.jol.util.VMSupport$2",
      "org.openjdk.jol.util.VMSupport$VMOptions",
      "org.openjdk.jol.util.MathUtil",
      "org.openjdk.jol.util.VMSupport$MyObject1",
      "org.openjdk.jol.util.VMSupport",
      "org.openjdk.jol.datamodel.CurrentDataModel",
      "org.openjdk.jol.info.FieldLayout",
      "io.airlift.slice.Slice",
      "io.airlift.slice.Slices",
      "com.google.common.collect.ImmutableCollection",
      "com.google.common.collect.ImmutableList",
      "com.google.common.collect.RegularImmutableList",
      "com.google.common.collect.Maps"
    );
  }
}
