/*
 * This file was automatically generated by EvoSuite
 * Sat Nov 20 17:40:05 GMT 2021
 */

package com.facebook.presto.resourceGroups.db;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import com.facebook.presto.resourceGroups.db.DbManagerSpecProvider;
import com.facebook.presto.resourceGroups.db.ResourceGroupsDao;
import com.facebook.presto.resourceGroups.reloading.ReloadingResourceGroupConfig;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class DbManagerSpecProvider_ESTest extends DbManagerSpecProvider_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      DbManagerSpecProvider dbManagerSpecProvider0 = null;
      try {
        dbManagerSpecProvider0 = new DbManagerSpecProvider((ResourceGroupsDao) null, "M", (ReloadingResourceGroupConfig) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // dao is null
         //
         verifyException("java.util.Objects", e);
      }
  }
}
